mods_feat(Nether Depths Upgrade) 2.0.2-1.19.2
xMikux/ModsTranslationPack pull request #312
Opened 2023-03-14 10:24 UTC by Jeffku0107

2023-03-20 13:06 UTC, StarskyXIII requested changes

2023-03-20 13:06 UTC, StarskyXIII commented on MultiVersions/Forge/main/netherdepthsupgrade/lang/zh_tw.json
> +  "itemGroup.netherdepthsupgrade_fish": "地獄深處升級：魚類",
```suggestion
  "itemGroup.netherdepthsupgrade_fish": "地獄深處升級｜魚類",
```
學當初 Scott 的提議，用｜來劃分

2023-03-20 13:06 UTC, StarskyXIII commented on MultiVersions/Forge/main/netherdepthsupgrade/lang/zh_tw.json
> +  "itemGroup.netherdepthsupgrade_food": "地獄深處升級：食物"
```suggestion
  "itemGroup.netherdepthsupgrade_food": "地獄深處升級：食物"
```
學當初 Scott 的提議，用｜來劃分

2023-03-21 09:52 UTC, Jeffku0107 commented on MultiVersions/Forge/main/netherdepthsupgrade/lang/zh_tw.json
> +  "itemGroup.netherdepthsupgrade_food": "地獄深處升級：食物"
但你沒改到 :trollface:

2023-03-30 17:36 UTC, StarskyXIII commented on MultiVersions/Forge/main/netherdepthsupgrade/lang/zh_tw.json
> +  "itemGroup.netherdepthsupgrade_food": "地獄深處升級：食物"
已修正

2023-03-30 17:51 UTC, StarskyXIII approved these changes

2023-03-30 17:51 UTC, merged