mods_feat(Creeper Overhaul): 新增苦力怕革新 v3.0.1
xMikux/ModsTranslationPack pull request #370
Opened 2023-09-04 22:47 UTC by Ylite-cola

2023-09-04 23:02 UTC, StarskyXIII requested changes

2023-09-04 23:02 UTC, StarskyXIII commented on MultiVersions/Fabric/main/creeper_overhaul/zh_tw.json
> +  "subtitles.creeperoverhaul.entity.wood.creeper.explosion": "苦力怕爆炸",
原版字幕的 `Explosion` 是譯作 `爆炸聲`，
詳情可參考這裡：
https://github.com/xMikux/ModsTranslationPack-Crowdin/blob/main/Vanilla-Translate/latest_tw.txt#L22587

2023-09-04 23:04 UTC, StarskyXIII commented
感謝對本專案貢獻，希望這些請求變更與建議不會嚇到你。

2023-09-04 23:32 UTC, Ylite-cola commented
> 感謝對本專案的貢獻，希望這些請求變更與建議不會嚇到你。布拉格 想請問一下，您已經加入我們的[Discord](https://discord.gg/7BbPMtygHU)服務器了嗎？ 方便後續翻譯上的交流，並給與您相應的譯者身體分組。

2023-09-04 23:33 UTC, Ylite-cola commented
謝謝~ 我剛看了一下，應該是我在PR的時候不小心動到甚麼，導致好幾個翻譯間都有空格，我在改一下

2023-09-04 23:40 UTC, Ylite-cola commented
> 感謝對本專案的貢獻，希望這些請求變更與建議不會嚇到你。布拉格 想請問一下，您已經加入我們的[Discord](https://discord.gg/7BbPMtygHU)服務器了嗎？ 方便後續翻譯上的交流，並給與您相應的譯者身體分組。

有喔，我的ID是yitite.luko 名稱是Yilite 再次感恩

2023-09-04 23:52 UTC, xMikux requested changes
你的結構驗證沒有通過，因為翻譯檔案放錯位置
通常來說是 ``{modID}/lang`` 你少了 lang 資料夾
還有其實 Forge/main 中已經包含此模組的翻譯，建議你也順便將檔案轉移到底下
感謝你的貢獻！

2023-09-05 00:49 UTC, StarskyXIII approved these changes
LGTM，感謝貢獻！

2023-09-05 01:02 UTC, xMikux approved these changes

2023-09-05 01:13 UTC, merged