mods_feat(More Geodes): 新增更多晶洞 v1.8.2
xMikux/ModsTranslationPack pull request #373
Opened 2023-09-05 09:50 UTC by Ylite-cola

2023-09-07 21:43 UTC, StarskyXIII commented on MultiVersions/Fabric/main/moregeodes/lang/zh_tw.json
> +    "block.geodes.emerald_crystal_block": "綠寶石晶體方塊",
只是好奇詢問
既然原版目前的晶簇只有紫水晶的話
`Crystal` 翻作 `水晶` 會不會比較有統一性

2023-09-08 09:05 UTC, Ylite-cola commented on MultiVersions/Fabric/main/moregeodes/lang/zh_tw.json
> +    "block.geodes.emerald_crystal_block": "綠寶石晶體方塊",
也可以，這樣感覺比較好~ 我改一下

2023-09-08 11:57 UTC, StarskyXIII requested changes

2023-09-08 11:57 UTC, StarskyXIII commented on MultiVersions/Fabric/main/moregeodes/lang/zh_tw.json
> +    "advancement.geodes.adventure.use_echo_locator.title": "這裡有回聲嗎?",
未使用全形符號
```suggestion
    "advancement.geodes.adventure.use_echo_locator.title": "這裡有回聲嗎？",

```

2023-09-08 11:57 UTC, StarskyXIII commented on MultiVersions/Fabric/main/moregeodes/lang/zh_tw.json
> +    "advancement.geodes.adventure.outrageous.description": "收集綠寶石晶洞方塊和鑽石晶洞方塊",
使句子閱讀起來較為簡潔
```suggestion
    "advancement.geodes.adventure.outrageous.description": "收集綠寶石與鑽石的晶洞方塊",

```

2023-09-08 14:03 UTC, StarskyXIII approved these changes

2023-09-09 19:12 UTC, xMikux approved these changes

2023-09-09 19:14 UTC, merged