mods_update(Enhanced Block Entities): 更新至 v0.9
xMikux/ModsTranslationPack pull request #377
Opened 2023-09-05 15:06 UTC by xMikux

2023-09-08 15:13 UTC, notlin4 commented on MultiVersions/Fabric/main/enhancedblockentities/lang/zh_tw.json
> +    "option.ebe.decorated_pot_ao": "平滑裝飾性盆栽光源",
"option.ebe.decorated_pot_ao": "平滑飾紋陶罐光源",

2023-09-08 15:23 UTC, notlin4 requested changes

2023-09-08 15:23 UTC, notlin4 commented on MultiVersions/Fabric/main/enhancedblockentities/lang/zh_tw.json
> +    "option.ebe.decorated_pot_ao.comment": "允許裝飾性盆栽使用平滑光源與環境遮蔽。需啟用「最佳化裝飾性盆栽」。",
Decorated Pot 的名稱為「飾紋陶罐」

2023-09-12 07:57 UTC, StarskyXIII requested changes

2023-09-12 07:57 UTC, StarskyXIII commented on MultiVersions/Fabric/main/enhancedblockentities/lang/zh_tw.json
> +    "option.ebe.render_enhanced_decorated_pots": "最佳化裝飾性盆栽",
```suggestion
    "option.ebe.render_enhanced_decorated_pots": "最佳化飾紋陶罐",
```

2023-09-12 07:57 UTC, StarskyXIII commented on MultiVersions/Fabric/main/enhancedblockentities/lang/zh_tw.json
> +    "option.ebe.render_enhanced_decorated_pots.comment": "啟用已處理過的裝飾性盆栽模型，在擁有大量裝飾性盆栽的區域大幅度提高效能。同時允許從遠處看到裝飾性盆栽。如果裝飾性盆栽變成隱形，或是模組版的盆栽圖樣沒有正確運作，請停用此最佳化。",
```suggestion
    "option.ebe.render_enhanced_decorated_pots.comment": "啟用已處理過的飾紋陶罐模型，在擁有大量飾紋陶罐的區域大幅度提高效能。同時允許從遠處看到飾紋陶罐。如果飾紋陶罐變成隱形，或是其他模組的陶罐紋樣沒有正確運作，請停用此最佳化。",
```

2023-09-12 07:57 UTC, StarskyXIII commented on MultiVersions/Fabric/main/enhancedblockentities/lang/zh_tw.json
> +    "option.ebe.decorated_pot_ao": "平滑裝飾性盆栽光源",
```suggestion
    "option.ebe.decorated_pot_ao": "平滑飾紋陶罐光源",
```

2023-09-12 07:57 UTC, StarskyXIII commented on MultiVersions/Fabric/main/enhancedblockentities/lang/zh_tw.json
> +    "option.ebe.force_resource_pack_compat.comment": "啟用這個當使用資源包時方塊變成隱形的情況。不要在資源包已設計為此模組情況下啟用。如果問題仍繼續發生，請回報給它們。",
```suggestion
    "option.ebe.force_resource_pack_compat.comment": "當使用的資源包造成方塊隱形時，請啟用該功能。不要在資源包已為此模組設計的情況下啟用。如果問題仍持續發生，請向資源包作者回報。",
```

2023-09-12 07:57 UTC, StarskyXIII commented on MultiVersions/Fabric/main/enhancedblockentities/lang/zh_tw.json
> +    "text.ebe.decorated_pot_options": "裝飾性盆栽選項",
```suggestion
    "text.ebe.decorated_pot_options": "飾紋陶罐選項",
```

2023-09-12 13:55 UTC, merged