mods_feat(Qualitys Delight): 新增優質樂事模組 v1.3.0
xMikux/ModsTranslationPack pull request #381
Opened 2023-09-06 04:39 UTC by Ylite-cola

農夫樂事和地獄樂事的內容是直接沿用這邊的翻譯
海洋樂事是部分沿用該模組附帶的翻譯

2023-09-07 19:26 UTC, StarskyXIII requested changes

2023-09-07 19:26 UTC, StarskyXIII commented on MultiVersions/Forge/main/qualitysdelight/lang/zh_tw.json
> +  "itemGroup.qualitysdelight.items": "優質樂事物品",
```suggestion
  "itemGroup.qualitysdelight.items": "優質樂事｜物品",
```

2023-09-07 19:26 UTC, StarskyXIII commented on MultiVersions/Forge/main/qualitysdelight/lang/zh_tw.json
> +  "itemGroup.qualitysdelight.nether_items": "地獄樂事物品",
```suggestion
  "itemGroup.qualitysdelight.nether_items": "地獄樂事｜物品",
```

2023-09-07 19:26 UTC, StarskyXIII commented on MultiVersions/Forge/main/qualitysdelight/lang/zh_tw.json
> +  "itemGroup.qualitysdelight.ocean_items": "海洋樂事物品",
```suggestion
  "itemGroup.qualitysdelight.ocean_items": "海洋樂事｜物品",
```

2023-09-07 19:26 UTC, StarskyXIII commented on MultiVersions/Forge/main/qualitysdelight/lang/zh_tw.json
> +  "itemGroup.qualitysdelight.respite_items": "農夫暇事物品"
```suggestion
  "itemGroup.qualitysdelight.respite_items": "農夫暇事｜物品"
```

2023-09-08 08:10 UTC, StarskyXIII commented on MultiVersions/Forge/main/qualitysdelight/lang/zh_tw.json
> +  "item.qualitysdelight.cooked_guardian_tail_diamond": "烤深海守衛尾",
我在想翻作 `尾鰭` 會不會比較順口，我知道這是該模組的內建翻譯，但就唸起來有點奇怪
```suggestion
  "item.qualitysdelight.cooked_guardian_tail_diamond": "烤深海守衛尾鰭",
```

2023-09-08 12:01 UTC, StarskyXIII approved these changes

2023-09-08 13:47 UTC, xMikux approved these changes

2023-09-08 14:14 UTC, merged