mods_feat(Horse Expert): 新增馬術專家 v8.0.1
xMikux/ModsTranslationPack pull request #385
Opened 2023-09-07 00:28 UTC by Ylite-cola

2023-09-07 19:16 UTC, StarskyXIII requested changes

2023-09-07 19:16 UTC, StarskyXIII commented on MultiVersions/Forge/main/horseexpert/lang/zh_tw.json
> +  "horse.tooltip.health": "生命值： %s",
多餘的空格
```suggestion
  "horse.tooltip.health": "生命值：%s",
```

2023-09-07 19:16 UTC, StarskyXIII commented on MultiVersions/Forge/main/horseexpert/lang/zh_tw.json
> +  "horse.tooltip.jump_height": "跳躍高度： %s",
多餘的空格
```suggestion
  "horse.tooltip.jump_height": "跳躍高度：%s",
```

2023-09-07 19:16 UTC, StarskyXIII commented on MultiVersions/Forge/main/horseexpert/lang/zh_tw.json
> +  "horse.tooltip.max": "最高： %s",
多餘的空格
```suggestion
  "horse.tooltip.max": "最高：%s",
```

2023-09-07 19:16 UTC, StarskyXIII commented on MultiVersions/Forge/main/horseexpert/lang/zh_tw.json
> +  "horse.tooltip.min": "最低： %s",
多餘的空格
```suggestion
  "horse.tooltip.min": "最低：%s",
```

2023-09-07 19:16 UTC, StarskyXIII commented on MultiVersions/Forge/main/horseexpert/lang/zh_tw.json
> +  "horse.tooltip.speed": "速度： %s",
多餘的空格
```suggestion
  "horse.tooltip.speed": "速度：%s",
```

2023-09-07 19:16 UTC, StarskyXIII commented on MultiVersions/Forge/main/horseexpert/lang/zh_tw.json
> +  "horse.tooltip.strength": "儲存： %s",
多餘的空格
```suggestion
  "horse.tooltip.strength": "儲存：%s",
```

2023-09-07 19:16 UTC, StarskyXIII commented on MultiVersions/Forge/main/horseexpert/lang/zh_tw.json
> +  "item.horseexpert.monocle.tooltip": "戴上它以查看坐騎的統計資訊!"
未使用全形標點符號
```suggestion
  "item.horseexpert.monocle.tooltip": "戴上眼鏡來查看坐騎的統計資訊！"
```

2023-09-08 08:04 UTC, StarskyXIII approved these changes

2023-09-08 14:45 UTC, xMikux approved these changes

2023-09-08 14:47 UTC, merged