mods_feat(Quality Crops): 新增優質作物 v1.0.5
xMikux/ModsTranslationPack pull request #386
Opened 2023-09-07 01:40 UTC by Ylite-cola

2023-09-07 19:09 UTC, StarskyXIII requested changes

2023-09-07 19:09 UTC, StarskyXIII commented on MultiVersions/Forge/main/qualitycrops/lang/zh_tw.json
> +  "itemGroup.qualitycrops.items": "優質作物物品"
當模組在創造模式中，有多個物品群組時，我們會習慣在模組名稱後，使用 `｜` 
```suggestion
  "itemGroup.qualitycrops.items": "優質作物｜物品"
```

2023-09-08 08:03 UTC, StarskyXIII approved these changes

2023-09-08 14:46 UTC, xMikux approved these changes

2023-09-08 14:47 UTC, merged