mods_feat(Let's Do: Meadow): 新增Let's Do: Meadow v1.3.1
xMikux/ModsTranslationPack pull request #398
Opened 2023-09-08 11:50 UTC by Ylite-cola

扭曲乳酪輪及伐木樁的翻譯是依照遊戲內的外觀。
"rei.meadow.fondue_category.amount":` "%s per fuel" 這條我自己在遊戲內沒找到實際的顯示位置，暫時先延用Jei的翻譯了，還有待修正

2023-09-10 22:32 UTC, StarskyXIII requested changes

2023-09-10 22:32 UTC, StarskyXIII commented on MultiVersions/Forge/main/letsdomeadow/lang/zh_tw.json
> +  "block.meadow.rack.tooltip": "可存放乳酪輪.",
![image](https://github.com/xMikux/ModsTranslationPack/assets/71606873/de751495-70f7-4c1d-b5bf-95b35745174b)
```suggestion
  "block.meadow.rack.tooltip": "用於貯存乳酪輪。",
```

2023-09-10 22:32 UTC, StarskyXIII commented on MultiVersions/Forge/main/letsdomeadow/lang/zh_tw.json
> +  "block.meadow.pine_wood": "松木",
```suggestion
  "block.meadow.pine_wood": "松木塊",
```

2023-09-10 22:32 UTC, StarskyXIII commented on MultiVersions/Forge/main/letsdomeadow/lang/zh_tw.json
> +  "meadow.tooltip.fur_armor2": "全套獎勵:",
```suggestion
  "meadow.tooltip.fur_armor2": "套裝加成：",
```

2023-09-10 22:32 UTC, StarskyXIII commented on MultiVersions/Forge/main/letsdomeadow/lang/zh_tw.json
> +  "meadow.tooltip.fur_armor": "毛皮盔甲:",
```suggestion
  "meadow.tooltip.fur_armor": "毛皮盔甲：",
```

2023-09-10 22:32 UTC, StarskyXIII commented on MultiVersions/Forge/main/letsdomeadow/lang/zh_tw.json
> +  "item.meadow.wooden_amethyst_milk_bucket": "木桶裝紫水晶...鮮奶？",
```suggestion
  "item.meadow.wooden_amethyst_milk_bucket": "紫水晶...鮮奶？木桶",
```

2023-09-10 22:32 UTC, StarskyXIII commented on MultiVersions/Forge/main/letsdomeadow/lang/zh_tw.json
> +  "item.meadow.ingredient.tooltipitem.meadow.wooden_amethyst_milk_bucket": "我們不知道這是誰想出的主意...",
~~讓句子充滿中二感~~
```suggestion
  "item.meadow.ingredient.tooltipitem.meadow.wooden_amethyst_milk_bucket": "無人知曉這是出自於誰的主意...",
```

2023-09-10 22:32 UTC, StarskyXIII commented on MultiVersions/Forge/main/letsdomeadow/lang/zh_tw.json
> +  "creativetab.meadow.tab": "Meadow",
我在想要不要將 `Let's Do` 譯作 `共度時光`，而這款模組是該系列中的「牧場」主題。
```suggestion
  "creativetab.meadow.tab": "共度時光｜牧場",
```

2023-09-10 22:32 UTC, StarskyXIII commented on MultiVersions/Forge/main/letsdomeadow/lang/zh_tw.json
> +  "block.meadow.wooden_bucket.tooltip": "主要用於替牛、綿羊、山羊擠奶",
正確的翻法
```suggestion
  "block.meadow.wooden_bucket.tooltip": "主要用於替牛、綿羊與山羊擠奶",
```

2023-09-10 22:32 UTC, StarskyXIII commented on MultiVersions/Forge/main/letsdomeadow/lang/zh_tw.json
> +  "entity.minecraft.villager.cheesemaker": "乳酪製造師",
不見得一定要採納，就覺得製造師怪怪的。
```suggestion
  "entity.minecraft.villager.cheesemaker": "乳酪達人",
```

2023-09-11 04:33 UTC, Ylite-cola commented on MultiVersions/Forge/main/letsdomeadow/lang/zh_tw.json
> +  "entity.minecraft.villager.cheesemaker": "乳酪製造師",
這個讚，我自己也覺得製造師很微妙，不過當時沒想到其他名稱

2023-09-11 04:34 UTC, Ylite-cola commented on MultiVersions/Forge/main/letsdomeadow/lang/zh_tw.json
> +  "entity.minecraft.villager.cheesemaker": "乳酪製造師",
這個讚，我自己也覺得製造師很微妙，不過當時沒想到其他名稱

2023-09-11 06:09 UTC, StarskyXIII approved these changes

2023-09-11 16:19 UTC, xMikux approved these changes

2023-09-11 16:20 UTC, merged