mods_feat(Etcetera): 新增Etcetera v2.1.1.3
xMikux/ModsTranslationPack pull request #400
Opened 2023-09-08 16:06 UTC by Ylite-cola

2023-09-08 16:50 UTC, Ylite-cola commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "item.minecraft.splash_potion.effect.sliding": "飛濺型滑溜藥水",
感恩~ 飛濺型是我直接從Minecraft Wiki:譯名標準化那邊看過來的，沒注意到問題

2023-09-08 16:54 UTC, StarskyXIII commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "item.minecraft.splash_potion.effect.sliding": "飛濺型滑溜藥水",
[這裡](https://github.com/xMikux/ModsTranslationPack-Crowdin/blob/main/Vanilla-Translate/latest_tw.txt) 是原文與遊戲內翻譯的對照表，建議參考這裡。
Minecraft Wiki 的內容，都是以簡體翻譯的用語為準，你所看到的繁體內容，都是經由網站的簡繁轉換表而來。
該轉換表只要沒人維護，上面呈現的繁體翻譯將可能是不準確或過時的。

2023-09-08 17:00 UTC, Ylite-cola commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "item.minecraft.splash_potion.effect.sliding": "飛濺型滑溜藥水",
謝謝~ 不過那個連結我點開來是顯示404耶

2023-09-08 17:01 UTC, StarskyXIII commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "item.minecraft.splash_potion.effect.sliding": "飛濺型滑溜藥水",
我忘記那儲存庫是私人專案了，還未公開 sry
這個是目前最新的對照表
[latest_tw.txt](https://github.com/xMikux/ModsTranslationPack/files/12562156/latest_tw.txt)

2023-09-08 17:10 UTC, Ylite-cola commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "item.minecraft.splash_potion.effect.sliding": "飛濺型滑溜藥水",
感謝~ 成功下載了

2023-09-10 21:27 UTC, StarskyXIII commented
標題打著 Etcetera，但實際上傳的內容是 Ecologics 模組 XD

2023-09-10 21:44 UTC, StarskyXIII requested changes

2023-09-10 21:44 UTC, StarskyXIII commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "block.ecologics.seashell_block": "貝殼磚",
磚應該會是 `Bricks`
```suggestion
  "block.ecologics.seashell_block": "貝殼方塊",
```

2023-09-10 21:44 UTC, StarskyXIII commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "block.ecologics.pot": "壺",
我看遊戲中是使用陶土合成，那麼叫做陶壺如何？
```suggestion
  "block.ecologics.pot": "陶壺",
```

2023-09-10 21:44 UTC, StarskyXIII commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "item.ecologics.coconut_slice": "椰子剖半",
剖半在這裡是形容詞，故應該放在名詞前面
```suggestion
  "item.ecologics.coconut_slice": "剖半的椰子",
```

2023-09-10 21:44 UTC, StarskyXIII commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "item.ecologics.walnut": "核桃樹",
他在遊戲裡的圖示是核桃
```suggestion
  "item.ecologics.walnut": "核桃",
```

2023-09-10 21:44 UTC, StarskyXIII commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "itemGroup.ecologics.tab": "Ecologics",
隨便想的名字
```suggestion
  "itemGroup.ecologics.tab": "自然生態",
```

2023-09-10 21:44 UTC, StarskyXIII commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "text.autoconfig.ecologics.title": "Ecologics 設定",
如果我想的模組名稱給過的話
```suggestion
  "text.autoconfig.ecologics.title": "《自然生態》設定",
```

2023-09-10 21:44 UTC, StarskyXIII commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "text.autoconfig.ecologics.option.beach.coconutCrabSpawnChance": "當椰子破碎時，椰子蟹的生成機率（百分比）為？",
去除贅字
```suggestion
  "text.autoconfig.ecologics.option.beach.coconutCrabSpawnChance": "當椰子破碎時，椰子蟹的生成機率（百分比）？",
```

2023-09-10 21:44 UTC, StarskyXIII commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "text.autoconfig.ecologics.option.desert.pricklyPearGrowthChance": "當仙人掌長到最高時，仙人掌果實的生長機率（百分比）為？",
去除贅字
```suggestion
  "text.autoconfig.ecologics.option.desert.pricklyPearGrowthChance": "當仙人掌長到最高時，仙人掌果實的生長機率（百分比）？",
```

2023-09-10 21:44 UTC, StarskyXIII commented on MultiVersions/Forge/main/ecologics/lang/zh_tw.json
> +  "text.autoconfig.ecologics.option.snowy.generateThinIcePatches": "生成薄冰區",
```suggestion
  "text.autoconfig.ecologics.option.snowy.generateThinIcePatches": "生成薄冰地區",
```

2023-09-11 05:50 UTC, StarskyXIII approved these changes

2023-09-11 15:25 UTC, xMikux approved these changes

2023-09-11 16:21 UTC, merged