mods_feat(Sushi.Go.Crafting): 新增巧製壽司 v0.3.8
xMikux/ModsTranslationPack pull request #403
Opened 2023-09-09 08:47 UTC by Ylite-cola

模組議名為簡中翻譯。不包含 Patchouli 手冊內容

2023-09-10 21:11 UTC, StarskyXIII requested changes

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.cleaver_knife": "砍刀",
```suggestion
  "item.sushigocrafting.cleaver_knife": "切肉刀",
```

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.tobiko": " 飛魚卵",
多餘的空格
```suggestion
  "item.sushigocrafting.tobiko": "飛魚卵",
```

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.tobiko_crab_california": " 飛魚卵蟹肉加州卷",
多餘的空格
```suggestion
  "item.sushigocrafting.tobiko_crab_california": "飛魚卵蟹肉加州卷",
```

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.tobiko_crab_cheese_california": " 飛魚卵蟹肉乳酪加州卷",
多餘的空格
```suggestion
  "item.sushigocrafting.tobiko_crab_cheese_california": "飛魚卵蟹肉乳酪加州卷",
```

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.tobiko_crab_cucumber_california": " 飛魚卵蟹肉黃瓜加州卷",
多餘的空格
```suggestion
  "item.sushigocrafting.tobiko_crab_cucumber_california": "飛魚卵蟹肉黃瓜加州卷",
```

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.tobiko_salmon_california": " 飛魚卵鮭魚加州卷",
多餘的空格
```suggestion
  "item.sushigocrafting.tobiko_salmon_california": "飛魚卵鮭魚加州卷",
```

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.tobiko_salmon_cheese_california": " 飛魚卵鮭魚乳酪加州卷",
多餘的空格
```suggestion
  "item.sushigocrafting.tobiko_salmon_cheese_california": "飛魚卵鮭魚乳酪加州卷",
```

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.tobiko_salmon_cucumber_california": " 飛魚卵鮭魚黃瓜加州卷",
多餘的空格
```suggestion
  "item.sushigocrafting.tobiko_salmon_cucumber_california": "飛魚卵鮭魚黃瓜加州卷",
```

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.tobiko_tuna_california": " 飛魚卵金槍魚加州卷",
多餘的空格
```suggestion
  "item.sushigocrafting.tobiko_tuna_california": "飛魚卵金槍魚加州卷",
```

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.tobiko_tuna_cheese_california": " 飛魚卵金槍魚乳酪加州卷",
多餘的空格
```suggestion
  "item.sushigocrafting.tobiko_tuna_cheese_california": "飛魚卵金槍魚乳酪加州卷",
```

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.tobiko_tuna_cucumber_california": " 飛魚卵槍魚黃瓜加州卷",
多餘的空格
```suggestion
  "item.sushigocrafting.tobiko_tuna_cucumber_california": "飛魚卵槍魚黃瓜加州卷",
```

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "text.sushigocrafting.book.title": "如何成為一位板前（巧製壽司手冊）"
加上《》，強調書名
```suggestion
  "text.sushigocrafting.book.title": "《如何成為一位板前》巧製壽司指南手冊"
```

2023-09-10 21:11 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.shrimp_bucket": "蝦桶",
這樣唸起來感覺比較順口（？
```suggestion
  "item.sushigocrafting.shrimp_bucket": "活蝦桶",
```

2023-09-11 05:43 UTC, StarskyXIII requested changes
應該是最後一個了

2023-09-11 05:43 UTC, StarskyXIII commented on MultiVersions/Forge/main/sushigocrafting/lang/zh_tw.json
> +  "item.sushigocrafting.onigiri": "握壽司",
他看起來比較像御飯糰
![image](https://github.com/xMikux/ModsTranslationPack/assets/71606873/a99c22fc-5eae-4c94-a058-2f5662eb7490)
```suggestion
  "item.sushigocrafting.onigiri": "御飯糰",
```

2023-09-11 10:21 UTC, StarskyXIII approved these changes
辛苦了

2023-09-11 14:37 UTC, xMikux approved these changes

2023-09-11 16:21 UTC, merged