mods_feat(ManyIdeas Core): 新增ManyIdeas Core模組 v1.4.2
xMikux/ModsTranslationPack pull request #419
Opened 2023-09-15 09:45 UTC by Ylite-cola

[https://secretsoft.de/mods/manyideas-core/](url) 作者的官方Wiki

### **可能有疑慮的：**

- **_"block.manyideas_core.debug_block_cullface": "Cullface 除錯方塊"_**
在 Minecraft Wiki 上沒找到專有譯名，採原文

- _**"death.attack.table_saw.player": "%1$s 在與 %2$s 戰鬥時到桌鋸上跳舞"**_
純粹沒想到比較好的翻法

- **_"main_messages_redstone_key_opened_by": "紅石鑰匙：開門方式",_**
正常應該是翻開啟方式，不過遊戲內只能拿來選擇開門方式，就翻成開門了，感覺有點彆扭還是標一下

2023-09-22 16:58 UTC, StarskyXIII requested changes

2023-09-22 16:58 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_core/lang/zh_tw.json
> +				"item.manyideas_core.panel_jungle": "叢林板",
```suggestion
				"item.manyideas_core.panel_jungle": "叢林木板",

```

2023-09-22 16:58 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_core/lang/zh_tw.json
> +						"message.manyideas_core.both.title": "雙種",
一般聽到的用法會是 `雙重` 或 `兩種`
```suggestion
						"message.manyideas_core.both.title": "兩種",

```

2023-09-22 16:58 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_core/lang/zh_tw.json
> +					"main_messages_redstone_key_opened_by_both": "開門方式：雙種",
一般聽到的用法會是 `雙重` 或 `兩種`
```suggestion
					"main_messages_redstone_key_opened_by_both": "開門方式：雙重",

```

2023-09-22 16:58 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_core/lang/zh_tw.json
> +				"main_blocks_vanilla_blocks_flowers_straight": "原版方塊：直立花朵",
~~不然要稱作~~ `置中花朵` ~~嗎~~

2023-09-23 14:28 UTC, Ylite-cola commented on MultiVersions/Forge/main/manyideas_core/lang/zh_tw.json
> +				"main_blocks_vanilla_blocks_flowers_straight": "原版方塊：直立花朵",
還是維持直立好了XD

2023-09-23 14:30 UTC, StarskyXIII commented
那個 `雙重` 我打錯了，應該是 `兩種` 才對，我很抱歉

2023-09-23 14:33 UTC, StarskyXIII approved these changes

2023-09-23 15:12 UTC, xMikux approved these changes

2023-09-23 15:28 UTC, merged