mods_feat(ManyIdeas Doors): 新增ManyIdeas Doors v1.2.3
xMikux/ModsTranslationPack pull request #434
Opened 2023-09-21 09:46 UTC by Ylite-cola

2023-09-22 16:48 UTC, StarskyXIII requested changes

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"block.manyideas_doors.big_door_terrace": "大型陽台鐵門",
```suggestion
					"block.manyideas_doors.big_door_terrace": "大型陽台拉門",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"block.manyideas_doors.big_door_birch": "大型形樺木門",
```suggestion
					"block.manyideas_doors.big_door_birch": "大型樺木門",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"block.manyideas_doors.door_acacia_shoji": "相思木拉門",
```suggestion
					"block.manyideas_doors.door_acacia_shoji": "相思木障子門",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"block.manyideas_doors.door_birch_shoji": "樺木拉門",
```suggestion
					"block.manyideas_doors.door_birch_shoji": "樺木障子門",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"block.manyideas_doors.door_crimson_shoji": "緋紅蕈木拉門",
```suggestion
					"block.manyideas_doors.door_crimson_shoji": "緋紅蕈木障子門",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"block.manyideas_doors.door_dark_oak_shoji": "黑橡木拉門",
```suggestion
					"block.manyideas_doors.door_dark_oak_shoji": "黑橡木障子門",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"block.manyideas_doors.door_jungle_shoji": "叢林木拉門",
```suggestion
					"block.manyideas_doors.door_jungle_shoji": "叢林木障子門",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"block.manyideas_doors.door_oak_shoji": "橡木拉門",
```suggestion
					"block.manyideas_doors.door_oak_shoji": "橡木障子門",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"block.manyideas_doors.door_spruce_shoji": "杉木拉門",
```suggestion
					"block.manyideas_doors.door_spruce_shoji": "杉木障子門",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"block.manyideas_doors.door_warped_shoji": "扭曲蕈木拉門",
```suggestion
					"block.manyideas_doors.door_warped_shoji": "扭曲蕈木障子門",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"block.manyideas_doors.door_iron_fantasy": " 幻想式鐵門",
```suggestion
					"block.manyideas_doors.door_iron_fantasy": "幻想式鐵門",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +			"main_blocks_player_door_sensor": "紅石方塊：玩家振測器門",
```suggestion
			"main_blocks_player_door_sensor": "紅石方塊：玩家偵測器",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +				"block.manyideas_doors.player_door_sensor": "玩家振測器門",
```suggestion
				"block.manyideas_doors.player_door_sensor": "玩家偵測器",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +				"main_messages_redstone_key_sensor_range": "紅石鑰匙：振測範圍",
```suggestion
				"main_messages_redstone_key_sensor_range": "紅石鑰匙：偵測範圍",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"main_messages_redstone_key_sensor_range_1": "振測範圍：1",
```suggestion
					"main_messages_redstone_key_sensor_range_1": "偵測範圍：1",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"main_messages_redstone_key_sensor_range_2": "振測範圍：2",
```suggestion
					"main_messages_redstone_key_sensor_range_2": "偵測範圍：2",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"message.manyideas_doors.sensor_range": "振測範圍",
```suggestion
					"message.manyideas_doors.sensor_range": "偵測範圍",

```

2023-09-22 16:48 UTC, StarskyXIII commented on MultiVersions/Forge/main/manyideas_doors/lang/zh_tw.json
> +					"main_messages_redstone_key_sensor_range_3": "振測範圍：3",
```suggestion
					"main_messages_redstone_key_sensor_range_3": "偵測範圍：3",

```

2023-09-23 13:45 UTC, StarskyXIII approved these changes

2023-09-23 15:14 UTC, xMikux approved these changes

2023-09-23 15:29 UTC, merged