mods_feat(Beautify!): 新增美化！ v2.0.1
xMikux/ModsTranslationPack pull request #436
Opened 2023-09-21 17:49 UTC by Ylite-cola

2023-09-22 18:08 UTC, StarskyXIII requested changes

2023-09-22 18:08 UTC, StarskyXIII commented on MultiVersions/Forge/main/beautify/lang/zh_tw.json
> +	"frame.description2": "按住 Shift 並對畫框右鍵可改變照片。",
純個人喜好：`Right Click` 翻作 `點擊右鍵`
```suggestion
	"frame.description2": "按住 Shift 並對畫框點擊右鍵，可改變照片。",

```

2023-09-22 18:08 UTC, StarskyXIII commented on MultiVersions/Forge/main/beautify/lang/zh_tw.json
> +	"candelabra.description2": "空手右鍵來熄燈。",
```suggestion
	"candelabra.description2": "空手對其點擊右鍵來熄燈。",

```

2023-09-22 18:08 UTC, StarskyXIII commented on MultiVersions/Forge/main/beautify/lang/zh_tw.json
> +	"blinds.description1": "右鍵可開啟或關閉相鄰的百葉窗。",
```suggestion
	"blinds.description1": "點擊右鍵來開啟或關閉相鄰的百葉窗。",

```

2023-09-22 18:08 UTC, StarskyXIII commented on MultiVersions/Forge/main/beautify/lang/zh_tw.json
> +	"trellis.description2": "可右鍵將植物栽種到格柵上。",
```suggestion
	"trellis.description2": "點擊右鍵來將植物栽種到格柵上。",

```

2023-09-23 14:31 UTC, StarskyXIII approved these changes

2023-09-23 15:17 UTC, xMikux approved these changes

2023-09-23 15:29 UTC, merged