mods_feat(Peculiars): 新增獨特風味 v4.0.1
xMikux/ModsTranslationPack pull request #439
Opened 2023-09-22 07:53 UTC by Ylite-cola

2023-09-22 16:09 UTC, StarskyXIII requested changes

2023-09-22 16:09 UTC, StarskyXIII commented on MultiVersions/Forge/main/peculiars/lang/zh_tw.json
> +  "item.peculiars.aloe_berry_smoothie": "蘆薈甜莓冰沙",
根據配方，他使用草莓合成製作。
![image](https://github.com/xMikux/ModsTranslationPack/assets/71606873/fd46e34a-cfac-4644-8b39-8898a2c51294)

```suggestion
  "item.peculiars.aloe_berry_smoothie": "蘆薈草莓冰沙",

```

2023-09-23 13:37 UTC, StarskyXIII approved these changes

2023-09-23 15:24 UTC, xMikux approved these changes

2023-09-23 15:30 UTC, merged