mods_feat(Numismatic Overhaul): 新增貨幣翻修 v0.2.10
xMikux/ModsTranslationPack pull request #450
Opened 2023-09-30 20:15 UTC by Ylite-cola

2023-09-30 20:23 UTC, StarskyXIII requested changes

2023-09-30 20:23 UTC, StarskyXIII commented on MultiVersions/Fabric/main/numismatic-overhaul/lang/zh_tw.json
> +  "item.numismatic-overhaul.bronze_coin": "銅幣",
```suggestion
  "item.numismatic-overhaul.bronze_coin": "青銅幣",
```

2023-09-30 20:42 UTC, StarskyXIII approved these changes

2023-10-01 07:13 UTC, xMikux approved these changes

2023-10-01 09:38 UTC, merged