mods_feat(Realm RPG: Pots & Mimics): 新增 Realm RPG：藏寶罐與偽裝蟹 v1.0.1
xMikux/ModsTranslationPack pull request #451
Opened 2023-09-30 20:29 UTC by Ylite-cola

2023-09-30 20:40 UTC, StarskyXIII requested changes
僅提供建議，非一定要採納

2023-09-30 20:40 UTC, StarskyXIII commented on MultiVersions/Forge/main/pots_and_mimics/lang/zh_tw.json
> +  "block.pots_and_mimics.decorative_end_pot": "裝飾終界藏寶罐",
這樣的效果應該會比較好（？
```suggestion
  "block.pots_and_mimics.decorative_end_pot": "終界藏寶罐（裝飾用）",
```

2023-09-30 20:40 UTC, StarskyXIII commented on MultiVersions/Forge/main/pots_and_mimics/lang/zh_tw.json
> +  "block.pots_and_mimics.decorative_nether_pot": "裝飾地獄藏寶罐",
```suggestion
  "block.pots_and_mimics.decorative_nether_pot": "地獄藏寶罐（裝飾用）",
```

2023-09-30 20:40 UTC, StarskyXIII commented on MultiVersions/Forge/main/pots_and_mimics/lang/zh_tw.json
> +  "block.pots_and_mimics.decorative_pot": "裝飾藏寶罐",
```suggestion
  "block.pots_and_mimics.decorative_pot": "藏寶罐（裝飾用）",
```

2023-09-30 20:56 UTC, StarskyXIII approved these changes

2023-10-01 07:14 UTC, xMikux approved these changes

2023-10-01 10:55 UTC, merged