mods_feat(Let's Do Beachparty): 共度時光｜沙灘派對 v1.1.2b
xMikux/ModsTranslationPack pull request #453
Opened 2023-09-30 20:54 UTC by Ylite-cola

2023-09-30 21:55 UTC, StarskyXIII requested changes

2023-09-30 21:55 UTC, StarskyXIII commented on MultiVersions/Forge/main/beachparty/lang/zh_tw.json
> +  "block.beachparty.sandwaves": "海浪沙",
用來形容沙的外觀的話，我感覺波浪比較合適
```suggestion
  "block.beachparty.sandwaves": "波浪沙",
```

2023-09-30 21:55 UTC, StarskyXIII commented on MultiVersions/Forge/main/beachparty/lang/zh_tw.json
> +  "block.beachparty.lounge_chair":"棕櫚木躺椅",
雖然功能上不能摺疊，但至少外觀上看起來可以 XD
跟 `Deck Chair` 的翻譯作區分
```suggestion
  "block.beachparty.lounge_chair":"棕櫚木折疊椅",
```

2023-09-30 21:55 UTC, StarskyXIII commented on MultiVersions/Forge/main/beachparty/lang/zh_tw.json
> +  "item.beachparty.overgrown_disc": "Overgrown 唱片",
一般都是歌曲名不翻譯而已，物品名稱盡量要有翻譯。
這翻譯是隨便想的，可以另外再想一個更合適的。
```suggestion
  "item.beachparty.overgrown_disc": "覆滿草枝的唱片",
```

2023-09-30 21:58 UTC, StarskyXIII requested changes

2023-09-30 21:58 UTC, StarskyXIII commented on MultiVersions/Forge/main/beachparty/lang/zh_tw.json
> +  "subtitles.beachparty.sound.ambient_beach": "海浪聲",
根據遊戲內實測，前面的 `subtitles.` 都要刪掉，不然字幕會顯示翻譯鍵。
原文也有同樣的問題。
所有字幕都是。
```suggestion
  "beachparty.sound.ambient_beach": "海浪聲",
```

2023-09-30 22:51 UTC, Ylite-cola commented on MultiVersions/Forge/main/beachparty/lang/zh_tw.json
> +  "item.beachparty.overgrown_disc": "Overgrown 唱片",
沒細看到，我還以為那是歌曲名 甘溫

2023-09-30 22:57 UTC, StarskyXIII approved these changes

2023-10-01 07:11 UTC, xMikux approved these changes

2023-10-01 10:53 UTC, merged