mods_feat(Atmospheric): 新增悠然一派 v5.0.0
xMikux/ModsTranslationPack pull request #457
Opened 2023-10-06 19:58 UTC by Ylite-cola

模組譯名是簡中翻譯
沒找到 Morado 的中文譯名（，用的是CFPA那邊的譯名

2023-10-24 21:02 UTC, StarskyXIII requested changes

2023-10-24 21:02 UTC, StarskyXIII commented on MultiVersions/Forge/main/atmospheric/lang/zh_tw.json
> +  "block.atmospheric.rosewood_boards": "花梨寬木材",
你在 Woodworks 模組那邊 `Board` 是翻作 `寬木板`，看要不要統一一下譯名。

2023-10-25 03:33 UTC, Ylite-cola commented on MultiVersions/Forge/main/atmospheric/lang/zh_tw.json
> +  "block.atmospheric.rosewood_boards": "花梨寬木材",
我統一成`寬木材`好了，`Board`外觀跟原版木材差不多

2023-10-25 03:33 UTC, Ylite-cola commented on MultiVersions/Forge/main/atmospheric/lang/zh_tw.json
> +  "block.atmospheric.aloe_bundle": "甘蔗塊",
~~好問題~~

2023-10-25 05:53 UTC, StarskyXIII requested changes

2023-10-25 05:53 UTC, StarskyXIII commented on MultiVersions/Forge/main/atmospheric/lang/zh_tw.json
> +  "block.atmospheric.kousa_boards": "棶木木寬木材",
```suggestion
  "block.atmospheric.kousa_boards": "棶木寬木材",

```

2023-10-25 12:48 UTC, StarskyXIII approved these changes

2023-10-25 13:21 UTC, xMikux approved these changes

2023-10-25 13:29 UTC, merged