mods_feat(Infinity Buttons): 新增無限按鈕 v4.0.1
xMikux/ModsTranslationPack pull request #462
Opened 2023-10-07 14:10 UTC by Ylite-cola

278 ~ 282 是 **_Upgrade Aquatic_** 的連動內容，沿用了 CFPA 那邊的譯名。

地獄樂事沿用這邊庫內的翻譯
夸克用 Grant88 的翻譯（基本上只要有注意到就會一律用他的

2023-10-08 01:31 UTC, xMikux requested changes
結構錯誤 少放一層 lang

2023-10-13 09:43 UTC, notlin4 requested changes

2023-10-14 08:55 UTC, notlin4 approved these changes

2023-10-16 08:59 UTC, notlin4 requested changes

2023-10-16 08:59 UTC, notlin4 commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "text.autoconfig.infinitybuttons.option.forceJadeHiding.@Tooltip[0]": "伺服器是否應在用戶端使用 Jude 時，強制隱藏用戶端對隱藏按鈕的資訊提示框",
```suggestion
  "text.autoconfig.infinitybuttons.option.forceJadeHiding.@Tooltip[0]": "伺服器是否應在用戶端使用 Jade 時，強制隱藏用戶端對隱藏按鈕的資訊提示框",

```

2023-10-25 11:56 UTC, StarskyXIII requested changes

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.fancy_emergency_button": "\u00A7c豪\u00A76a\u00A7e華\u00A7ac\u00A7炫\u00A79E\u00A7d彩\u00A7ce\u00A76緊\u00A7eg\u00A7a急\u00A7bn\u00A79按\u00A7dy \u00A7c鈕",
![image](https://github.com/xMikux/ModsTranslationPack/assets/71606873/aa7dfb37-3ffb-4e61-83ad-8fe489b8fd27)

```suggestion
  "block.infinitybuttons.fancy_emergency_button": "\u00A7c豪\u00A76\u00A7e華\u00A7a\u00A7炫\u00A79\u00A7d彩\u00A7c\u00A76緊\u00A7e\u00A7a急\u00A7b\u00A79按\u00A7d\u00A7c鈕",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.lamp_button": "紅石燈按鈕（自動關閉）",
```suggestion
  "block.infinitybuttons.lamp_button": "紅石燈按鈕（自動復位）",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.letter_button": "字母按鈕（自動關閉）",
```suggestion
  "block.infinitybuttons.letter_button": "字母按鈕（自動復位）",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.lamp_lever": "紅石燈按鈕（常亮）",
```suggestion
  "block.infinitybuttons.lamp_lever": "紅石燈按鈕（兩段式）",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.letter_lever": "字母按鈕按鈕（常亮）",
```suggestion
  "block.infinitybuttons.letter_lever": "字母按鈕按鈕（兩段式）",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.small_console_lever": "小型儀表板按鈕（常亮）",
```suggestion
  "block.infinitybuttons.small_console_lever": "小型儀表板按鈕（兩段式）",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.console_lever": "儀表板按鈕（常亮）",
```suggestion
  "block.infinitybuttons.console_lever": "儀表板按鈕（兩段式）",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.large_console_lever": "大型儀表板按鈕（常亮）",
```suggestion
  "block.infinitybuttons.large_console_lever": "大型儀表板按鈕（兩段式）",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.big_console_lever": "大型儀表板按鈕（常亮）",
```suggestion
  "block.infinitybuttons.big_console_lever": "大型儀表板按鈕（兩段式）",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.big_console_button": "大型儀表板按鈕（自動關閉）",
```suggestion
  "block.infinitybuttons.big_console_button": "大型儀表板按鈕（自動復位）",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.large_console_button": "大型儀表板按鈕（自動關閉）",
```suggestion
  "block.infinitybuttons.large_console_button": "大型儀表板按鈕（自動復位）",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.console_button": "儀表板按鈕（自動關閉）",
```suggestion
  "block.infinitybuttons.console_button": "儀表板按鈕（自動復位）",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.small_console_button": "小型儀表板按鈕（自動關閉）",
```suggestion
  "block.infinitybuttons.small_console_button": "小型儀表板按鈕（自動復位）",

```

2023-10-25 11:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "infinitybuttons.subtitle.stone_scrape": "石磚摩擦擦",
~~疊字字~~
```suggestion
  "infinitybuttons.subtitle.stone_scrape": "石磚摩擦聲",

```

2023-10-31 00:27 UTC, StarskyXIII requested changes

2023-10-31 00:27 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.fancy_emergency_button": "\u00A7c豪\u00A76\u00A7e華\u00A7a\u00A7炫\u00A79\u00A7d彩\u00A7c\u00A76緊\u00A7e\u00A7a急\u00A7b\u00A79按\u00A7d\u00A7c鈕",
炫被吃掉ㄌ
![image](https://github.com/xMikux/ModsTranslationPack/assets/71606873/de6803da-c69f-46b7-9cbd-b4394a523a4c)
```suggestion
  "block.infinitybuttons.fancy_emergency_button": "\u00A7c豪\u00A76\u00A7e華\u00A7a\u00A7b炫\u00A79\u00A7d彩\u00A7c\u00A76緊\u00A7e\u00A7a急\u00A7b\u00A79按\u00A7d\u00A7c鈕",

```

2023-10-31 00:27 UTC, StarskyXIII commented on MultiVersions/Forge/main/infinitybuttons/lang/zh_tw.json
> +  "block.infinitybuttons.fancy_safe_emergency_button": "\u00A7c豪\u00A76\u00A7e華\u00A7a\u00A7炫\u00A79\u00A7d彩\u00A7c\u00A76緊\u00A7e\u00A7a急\u00A7b\u00A79按\u00A7d\u00A7c鈕",
炫被吃掉ㄌ
![image](https://github.com/xMikux/ModsTranslationPack/assets/71606873/dc63d7f7-ed81-4b90-b3d9-8356a4500104)

```suggestion
  "block.infinitybuttons.fancy_safe_emergency_button": "\u00A7c豪\u00A76\u00A7e華\u00A7a\u00A7b炫\u00A79\u00A7d彩\u00A7c\u00A76緊\u00A7e\u00A7a急\u00A7b\u00A79按\u00A7d\u00A7c鈕",

```

2023-10-31 03:17 UTC, StarskyXIII approved these changes
![image](https://github.com/xMikux/ModsTranslationPack/assets/71606873/ba8fa28e-422b-49dc-9d34-810dec4c13aa)

2023-11-02 10:45 UTC, xMikux approved these changes

2023-11-02 10:49 UTC, merged