mods_feat(Autumnity): 新增秋意楓林 v4.0.1
xMikux/ModsTranslationPack pull request #466
Opened 2023-10-07 19:41 UTC by Ylite-cola

`南瓜組塊`的作用是像釉陶那樣可以自己拚出一個大南瓜圖案
`穢莓` 也可以譯成`臭味莓`、`臭莓`，意思都一樣，可以順便看看哪個比較好
模組譯名和`黃楓點綴森林`來自 grant88 的該模組翻譯文章頁面

  **_"subtitles.autumnity.block.turkey.cut": "Cutting turkey",_** 
這個我找不到實際出現在哪（ 

~~翻完才發現跟 grant88 撞車 ，還好他那邊是翻 1.18 到低版本、版本號也到 v3.0.0 而已 不然真的會氣死~~

2023-10-25 12:30 UTC, StarskyXIII requested changes

2023-10-25 12:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/autumnity/lang/zh_tw.json
> +  "block.autumnity.pancake": " 楓糖漿鬆餅",
```suggestion
  "block.autumnity.pancake": "楓糖漿鬆餅",

```

2023-10-25 12:43 UTC, StarskyXIII requested changes

2023-10-25 12:43 UTC, StarskyXIII commented on MultiVersions/Forge/main/autumnity/lang/zh_tw.json
> +  "subtitles.autumnity.block.turkey.cut": "火雞肉切塊",
> "subtitles.autumnity.block.turkey.cut": "Cutting turkey",
這個我找不到實際出現在哪（

驗證了一下，你可以把火雞肉放在世界上，然後用 Farmer's Delight 的菜刀把肉切成雞腿
```suggestion
  "subtitles.autumnity.block.turkey.cut": "切火雞肉",

```

2023-10-27 19:16 UTC, StarskyXIII approved these changes

2023-10-31 11:10 UTC, xMikux approved these changes

2023-10-31 11:10 UTC, merged