mods_feat(Progressive Bosses): Boss 難度漸增 v.3.7.5
xMikux/ModsTranslationPack pull request #472
Opened 2023-10-09 12:40 UTC by obscure-man

2023-10-25 12:25 UTC, StarskyXIII requested changes

2023-10-25 12:25 UTC, StarskyXIII commented on MultiVersions/Forge/main/progressivebosses/lang/zh_tw.json
> +  "progressivebosses:command.player_get_dragon_difficulty": "%s 殺了 %d 條終界龍",
```suggestion
  "progressivebosses:command.player_get_dragon_difficulty": "%s 殺死了 %d 條終界龍",

```

2023-10-25 12:25 UTC, StarskyXIII commented on MultiVersions/Forge/main/progressivebosses/lang/zh_tw.json
> +  "dragon.first_killed": "恭喜你第一次殺了終界龍，之後的每條龍都會比前一條還難打了喔。",
```suggestion
  "dragon.first_killed": "恭喜你第一次殺死終界龍，之後的每條龍都會比前一條更加難以攻略。",

```

2023-10-25 12:25 UTC, StarskyXIII commented on MultiVersions/Forge/main/progressivebosses/lang/zh_tw.json
> +  "wither.first_summon": "你第一次召喚了凋零怪，要注意之後召喚的每隻凋零怪都會比前一隻還難打。",
```suggestion
  "wither.first_summon": "這是你第一次召喚凋零怪，要注意之後召喚的每隻凋零怪都會比前一隻更加難以攻略。",

```

2023-10-26 10:43 UTC, StarskyXIII approved these changes

2023-10-26 10:48 UTC, xMikux approved these changes

2023-10-26 11:16 UTC, merged