mods_feat(Difficult Raids): 突襲加強 v.1.19.2-2.0-beta.11
xMikux/ModsTranslationPack pull request #478
Opened 2023-10-10 08:59 UTC by obscure-man

2023-10-25 12:18 UTC, StarskyXIII requested changes

2023-10-25 12:18 UTC, StarskyXIII commented on MultiVersions/Forge/main/difficultraids/lang/zh_tw.json
> +    "item.difficultraids.levitation_totem": "漂浮圖騰",
```suggestion
    "item.difficultraids.levitation_totem": "懸浮圖騰",
```

2023-10-25 12:18 UTC, StarskyXIII commented on MultiVersions/Forge/main/difficultraids/lang/zh_tw.json
> +    "entity.difficultraids.shaman_debuff_bullet": "減損效果子彈",
```suggestion
    "entity.difficultraids.shaman_debuff_bullet": "薩滿的負面效果子彈",
```

2023-10-26 10:43 UTC, StarskyXIII approved these changes

2023-10-26 10:47 UTC, xMikux approved these changes

2023-10-26 11:06 UTC, merged