mods_feat(Integrated Dynamics): 整合動力 v.1.19.2-1.20.0
xMikux/ModsTranslationPack pull request #494
Opened 2023-10-29 13:50 UTC by obscure-man

1. 手冊翻譯沒翻，我也應該不會想翻（真的有人會看嗎）
2. 沒翻譯的部分不是我在遊戲找不到就是我不知道它在幹啥，我不太敢動，雖然很不負責任，但是歡迎各位譯者補充。（如果能附上例子讓我理解那更好了）
3. 還有連動模組的部分我盡量早點補上

2024-04-05 12:51 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "block.integrateddynamics.energy_battery.info": "和其他儲電箱合成能夠增加容量，Shift + 右鍵可以開啟自動供應模式。",
原文與譯文皆為按下**Shift**，但實際上模組是識別**潛行**，如此翻譯較能避免誤導。
```suggestion
    "block.integrateddynamics.energy_battery.info": "和其他儲電箱合成能夠增加容量，潛行 + 按下右鍵可以開啟自動供應模式。",
```

2024-04-05 12:52 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "item.integrateddynamics.wrench.info": "Shift + 右鍵以切換模式",
原文與譯文皆為按下**Shift**，但實際上模組是識別**潛行**，如此翻譯較能避免誤導。
```suggestion
    "item.integrateddynamics.wrench.info": "潛行 + 按下右鍵以切換模式",
```

2024-04-05 12:53 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "item.integrateddynamics.wrench.mode.offset.info": "Shift + 右鍵一個位置，再右建設配來設定偏移量。",
原文為按下**Shift**，但實際上模組是識別**潛行**，如此翻譯較能避免誤導。
**右建設配**應為**右鍵設備**
```suggestion
    "item.integrateddynamics.wrench.mode.offset.info": "潛行 + 按下右鍵一個位置，再右建設配來設定偏移量。",
```

2024-04-05 12:54 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "item.integrateddynamics.wrench.mode.offset_side.info": "Shift + 右鍵一個位置，再右建設配來設定偏移量和方位。",
原文為按下**Shift**，但實際上模組是識別**潛行**，如此翻譯較能避免誤導。
```suggestion
    "item.integrateddynamics.wrench.mode.offset_side.info": "潛行 + 按下右鍵一個位置，再右建設配來設定偏移量和方位。",
```

2024-04-05 12:56 UTC, StarskyXIII commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "item.integrateddynamics.wrench.mode.offset.info": "Shift + 右鍵一個位置，再右建設配來設定偏移量。",
該段句子使用 `右鍵點擊`，能使語義較為流暢
```suggestion
    "item.integrateddynamics.wrench.mode.offset.info": "Shift + 右鍵點擊一個位置，再對著設備點擊右鍵來設定偏移量。",
```

2024-04-05 12:57 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.double": "倍精準度浮點數",
**double-precision**普遍譯作**雙精度**
```suggestion
    "operator.integrateddynamics.double": "雙精度浮點數",
```

2024-04-05 12:58 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.nbt.compound_with_double": "添加子標籤（倍精準度浮點數）",
**double-precision**普遍譯作**雙精度**
```suggestion
    "operator.integrateddynamics.nbt.compound_with_double": "添加子標籤（雙精度浮點數）",
```

2024-04-05 12:58 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.nbt.compound_with_double.info": "複製一份加上給定倍精準度浮點數類型標籤的 NBT 複合標籤",
**double-precision**普遍譯作**雙精度**
```suggestion
    "operator.integrateddynamics.nbt.compound_with_double.info": "複製一份加上給定雙精度浮點數類型標籤的 NBT 複合標籤",
```

2024-04-05 12:59 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.nbt.as_double.info": "將倍精準度浮點數類型的標籤值轉為倍精準度浮點數值",
**double-precision**普遍譯作**雙精度**
```suggestion
    "operator.integrateddynamics.nbt.as_double.info": "將雙精度浮點數類型的標籤值轉為雙精度浮點數值",
```

2024-04-05 12:59 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.nbt.as_float": "標籤（單精準度浮點數）值轉為倍精準度浮點數值",
**double-precision**普遍譯作**雙精度**
```suggestion
    "operator.integrateddynamics.nbt.as_float": "標籤（單精準度浮點數）值轉為雙精度浮點數值",
```

2024-04-05 13:00 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.nbt.as_float.info": "將單精準度浮點數類型的標籤值轉為倍精準度浮點數值",
**double-precision**普遍譯作**雙精度**
```suggestion
    "operator.integrateddynamics.nbt.as_float.info": "將單精準度浮點數類型的標籤值轉為雙精度浮點數值",
```

2024-04-05 13:00 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.nbt.from_double": "倍精準度浮點數值轉為標籤（倍精準度浮點數）值",
**double-precision**普遍譯作**雙精度**
```suggestion
    "operator.integrateddynamics.nbt.from_double": "雙精度浮點數值轉為標籤（雙精度浮點數）值",
```

2024-04-05 13:01 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.nbt.from_double.info": "將倍精準度浮點數值轉為倍精準度浮點數類型的標籤值",
**double-precision**普遍譯作**雙精度**
```suggestion
    "operator.integrateddynamics.nbt.from_double.info": "將雙精度浮點數值轉為雙精度浮點數類型的標籤值",
```

2024-04-05 13:01 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.nbt.from_float": "倍精準度浮點數值轉為標籤（單精準度浮點數）值",
**double-precision**普遍譯作**雙精度**
```suggestion
    "operator.integrateddynamics.nbt.from_float": "雙精度浮點數值轉為標籤（單精準度浮點數）值",
```

2024-04-05 13:01 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.nbt.from_float.info": "將倍精準度浮點數值轉為單精準度浮點數類型的標籤值",
**double-precision**普遍譯作**雙精度**
```suggestion
    "operator.integrateddynamics.nbt.from_float.info": "將雙精度浮點數值轉為單精準度浮點數類型的標籤值",
```

2024-04-05 13:02 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.nbt.compound_with_float": "添加子標籤（單精準度浮點數）",
**single-precision*普遍譯作**單精度**
```suggestion
    "operator.integrateddynamics.nbt.compound_with_float": "添加子標籤（單精度浮點數）",
```

2024-04-05 13:03 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.nbt.compound_with_float.info": "複製一份加上給定單精準度浮點數類型標籤的 NBT 複合標籤",
**single-precision*普遍譯作**單精度**
```suggestion
    "operator.integrateddynamics.nbt.compound_with_float.info": "複製一份加上給定單精度浮點數類型標籤的 NBT 複合標籤",
```

2024-04-05 13:05 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.arithmetic.modulus": "模數",
**餘數**更易於理解
```suggestion
    "operator.integrateddynamics.arithmetic.modulus": "餘數",
```

2024-04-05 13:06 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.integer.modulus": "模數",
**餘數**更易於理解
```suggestion
    "operator.integrateddynamics.integer.modulus": "餘數",
```

2024-04-05 13:09 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.read.integer.extradimensional.ticktime": "每刻時間",
參考**frametime**翻譯，加入「此數值為計算每一刻所耗費之時間」的概念
```suggestion
    "aspect.integrateddynamics.read.integer.extradimensional.ticktime": "每刻耗時",
```

2024-04-05 13:13 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.read.integer.world.raincountdown.info": "此世界在幾 tick 後會下雨",
參考原版將**tick**譯作**刻**
```suggestion
    "aspect.integrateddynamics.read.integer.world.raincountdown.info": "此世界在幾刻後會下雨",
```

2024-04-05 13:15 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.read.integer.world.ticktime.info": "此世界平均每 tick 的時間（ms）",
參考**frametime**翻譯，加入「此數值為計算每一刻所耗費之時間」的概念
考量其他地方也可能出現單位**ms**，故保持英文以確保統一性
```suggestion
    "aspect.integrateddynamics.read.integer.world.ticktime.info": "此世界平均每刻耗時（ms）",
```

2024-04-05 13:16 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.read.double.world.tps.info": "此世界一秒的 tick 數",
參考原版將**tick**譯作**刻**
```suggestion
    "aspect.integrateddynamics.read.double.world.tps.info": "此世界一秒的刻數",
```

2024-04-05 13:17 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.itemstack.burntime.info": "物品作為燃料的燃燒時長（tick）",
參考原版將**tick**譯作**刻**
```suggestion
    "operator.integrateddynamics.itemstack.burntime.info": "物品作為燃料的燃燒時長（刻）",
```

2024-04-05 13:18 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.read.boolean.machine.isworker.info": "檢查目標是否為工作方塊（譯者註：工作方塊大致上為需要時間處理配方的方塊，如熔爐、營火等。但是基本上只支持原版和整合動力的方塊。）",
台灣習慣用詞為**支援**
```suggestion
    "aspect.integrateddynamics.read.boolean.machine.isworker.info": "檢查目標是否為工作方塊（譯者註：工作方塊大致上為需要時間處理配方的方塊，如熔爐、營火等。但是基本上只支援原版和整合動力的方塊。）",
```

2024-04-05 13:19 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "advancement.integrateddynamics.smart_pressure_plate": "智能壓力板",
台灣習慣用詞為**智慧**
```suggestion
    "advancement.integrateddynamics.smart_pressure_plate": "智慧壓力板",
```

2024-04-05 13:20 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "block.integrateddynamics.mechanical_drying_basin.info": "用電力將物品和液體晾乾",
**晾乾**是自然乾燥，改用**烘乾**較為合理
```suggestion
    "block.integrateddynamics.mechanical_drying_basin.info": "用電力將物品和液體烘乾",
```

2024-04-05 13:20 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "item.integrateddynamics.wrench": "板手",
錯字，應為**扳手**
```suggestion
    "item.integrateddynamics.wrench": "扳手",
```

2024-04-05 13:20 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "item.integrateddynamics.wrench.mode.offset.incomplete": "板手還沒設定位置",
錯字，應為**扳手**
```suggestion
    "item.integrateddynamics.wrench.mode.offset.incomplete": "扳手還沒設定位置",
```

2024-04-05 13:21 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.general.choice.info": "如果第一項的值為 True，就取第二項的值，否則取第三項的值 \\n第二項和第三項的值類型必須相同",
**true**應為全小寫
```suggestion
    "operator.integrateddynamics.general.choice.info": "如果第一項的值為 true，就取第二項的值，否則取第三項的值 \\n第二項和第三項的值類型必須相同",
```

2024-04-05 13:21 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "parttype.integrateddynamics.connector_mono_directional.info": "在直線上連接另一個遠處的單通道連結器",
**連結器**應為**連接器**
```suggestion
    "parttype.integrateddynamics.connector_mono_directional.info": "在直線上連接另一個遠處的單通道連接器",
```

2024-04-05 13:22 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.read.boolean.world.weather.raining.info": "檢查天氣是否為晴天",
**晴天**應為**雨天**
```suggestion
    "aspect.integrateddynamics.read.boolean.world.weather.raining.info": "檢查天氣是否為雨天",
```

2024-04-05 13:24 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_ambient_entity_effect.info": "以特定速率釋放烽火台效果粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_ambient_entity_effect.info": "指定烽火台粒子效果的釋放速度",
```

2024-04-05 13:25 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_bubble.info": "以特定速率釋放氣泡粒子",
指定氣泡粒子效果的釋放速度

2024-04-05 13:25 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_cloud.info": "以特定速率釋放煙霧粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_cloud.info": "指定煙霧粒子效果的釋放速度",
```

2024-04-05 13:26 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_bubble.info": "以特定速率釋放氣泡粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_bubble.info": "指定氣泡粒子效果的釋放速度",
```

2024-04-05 13:26 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_crit.info": "以特定速率釋放爆擊粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_crit.info": "指定爆擊粒子效果的釋放速度",
```

2024-04-05 13:26 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_damage_indicator.info": "以特定速率釋放傷害指示粒子",
指定傷害指示粒子效果的釋放速度

2024-04-05 13:26 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dragon_breath.info": "以特定速率釋放龍之吐息粒子",
指定龍之吐息粒子效果的釋放速度

2024-04-05 13:27 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dragon_breath.info": "以特定速率釋放龍之吐息粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dragon_breath.info": "指定龍之吐息粒子效果的釋放速度",
```

2024-04-05 13:28 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_lava.info": "以特定速率釋放熔岩滴落粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_lava.info": "指定熔岩滴落粒子效果的釋放速度",
```

2024-04-05 13:29 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dripping_water.info": "以特定速率釋放水滲出粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dripping_water.info": "指定水滲出粒子效果的釋放速度",
```

2024-04-05 13:29 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_water.info": "以特定速率釋放水滴落粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_water.info": "指定水滴落粒子效果的釋放速度",
```

2024-04-05 13:29 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_effect.info": "以特定速率釋放藥水效果粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_effect.info": "指定藥水效果粒子效果的釋放速度",
```

2024-04-05 13:32 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_enchanted_hit.info": "以特定速率釋放附魔打擊粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_enchanted_hit.info": "指定附魔打擊粒子效果的釋放速度",
```

2024-04-05 13:36 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_end_rod.info": "以特定速率釋放終界燭粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_end_rod.info": "指定終界燭粒子效果的釋放速度",
```

2024-04-05 13:36 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_entity_effect.info": "以特定速率釋放藥水效果（實體）粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_entity_effect.info": "指定藥水效果（實體）粒子效果的釋放速度",
```

2024-04-05 13:36 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_explosion_emitter.info": "以特定速率釋放爆炸（大）粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_explosion_emitter.info": "指定爆炸（大）粒子效果的釋放速度",
```

2024-04-05 13:36 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_sonic_boom.info": "以特定速率釋放音波粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_sonic_boom.info": "指定音波粒子效果的釋放速度",
```

2024-04-05 13:37 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_fishing.info": "以特定速率釋放釣魚粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_fishing.info": "指定釣魚粒子效果的釋放速度",
```

2024-04-05 13:37 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_flame.info": "以特定速率釋放火苗粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_flame.info": "指定火苗粒子效果的釋放速度",
```

2024-04-05 13:37 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_soul_fire_flame.info": "以特定速率釋放靈魂火苗粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_soul_fire_flame.info": "指定靈魂火苗粒子效果的釋放速度",
```

2024-04-05 13:38 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_sculk_charge_pop.info": "以特定速率釋放伏聆泡泡粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_sculk_charge_pop.info": "指定伏聆泡泡粒子效果的釋放速度",
```

2024-04-05 13:38 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_flash.info": "以特定速率釋放煙火爆炸粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_flash.info": "指定煙火爆炸粒子效果的釋放速度",
```

2024-04-05 13:38 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_composter.info": "以特定速率釋放堆肥桶粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_composter.info": "指定堆肥桶粒子效果的釋放速度",
```

2024-04-05 13:38 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_heart.info": "以特定速率釋放愛心粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_heart.info": "指定愛心粒子效果的釋放速度",
```

2024-04-05 13:38 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_instant_effect.info": "以特定速率釋放立即藥水效果粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_instant_effect.info": "指定立即藥水效果粒子效果的釋放速度",
```

2024-04-05 13:39 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_item_slime.info": "以特定速率釋放史萊姆粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_item_slime.info": "指定史萊姆粒子效果的釋放速度",
```

2024-04-05 13:39 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_item_snowball.info": "以特定速率釋放雪球粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_item_snowball.info": "指定雪球粒子效果的釋放速度",
```

2024-04-05 13:39 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_large_smoke.info": "以特定速率釋放煙霧（大）粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_large_smoke.info": "指定煙霧（大）粒子效果的釋放速度",
```

2024-04-05 13:40 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_mycelium.info": "以特定速率釋放菌絲土孢子粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_mycelium.info": "指定菌絲土孢子粒子效果的釋放速度",
```

2024-04-05 13:40 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_note.info": "以特定速率釋放音符粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_note.info": "指定音符粒子效果的釋放速度",
```

2024-04-05 13:40 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_poof.info": "以特定速率釋放死亡煙霧粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_poof.info": "指定死亡煙霧粒子效果的釋放速度",
```

2024-04-05 13:40 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_portal.info": "以特定速率釋放傳送門粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_portal": "粒子效果：傳送門",
```

2024-04-05 13:41 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_rain.info": "以特定速率釋放雨滴落地粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_rain.info": "指定雨滴落地粒子效果的釋放速度",
```

2024-04-05 13:41 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_smoke.info": "以特定速率釋放黑煙粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_smoke.info": "指定黑煙粒子效果的釋放速度",
```

2024-04-05 13:41 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_spit.info": "以特定速率釋放駱馬口水粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_spit.info": "指定駱馬口水粒子效果的釋放速度",
```

2024-04-05 13:41 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_squid_ink.info": "以特定速率釋放魷魚噴墨粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_squid_ink.info": "指定魷魚噴墨粒子效果的釋放速度",
```

2024-04-05 13:42 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_sweep_attack.info": "以特定速率釋放橫掃攻擊粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_sweep_attack.info": "指定橫掃攻擊粒子效果的釋放速度",
```

2024-04-05 13:42 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_totem_of_undying.info": "以特定速率釋放不死圖騰粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_totem_of_undying.info": "指定不死圖騰粒子效果的釋放速度",
```

2024-04-05 13:42 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_underwater.info": "以特定速率釋放水下微粒粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_underwater.info": "指定水下微粒粒子效果的釋放速度",
```

2024-04-05 13:42 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_splash.info": "以特定速率釋放小水花粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_splash.info": "指定小水花粒子效果的釋放速度",
```

2024-04-05 13:43 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_witch.info": "以特定速率釋放女巫粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_witch.info": "指定女巫粒子效果的釋放速度",
```

2024-04-05 13:43 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_bubble_pop.info": "以特定速率釋放氣泡破裂粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_bubble_pop.info": "指定氣泡破裂粒子效果的釋放速度",
```

2024-04-05 13:43 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_current_down.info": "以特定速率釋放氣泡下降粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_current_down.info": "指定氣泡下降粒子效果的釋放速度",
```

2024-04-05 13:43 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_bubble_column_up.info": "以特定速率釋放氣泡上升粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_bubble_column_up.info": "指定氣泡上升粒子效果的釋放速度",
```

2024-04-05 13:44 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_nautilus.info": "以特定速率釋放海靈核心粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_nautilus.info": "指定海靈核心粒子效果的釋放速度",
```

2024-04-05 13:44 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dolphin.info": "以特定速率釋放海豚粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dolphin.info": "指定海豚粒子效果的釋放速度",
```

2024-04-05 13:44 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_campfire_signal_smoke.info": "以特定速率釋放營火煙霧（乾草捆）粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_campfire_signal_smoke.info": "指定營火煙霧（乾草捆）粒子效果的釋放速度",
```

2024-04-05 13:45 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dripping_honey.info": "以特定速率釋放蜂蜜滲出粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dripping_honey.info": "指定蜂蜜滲出粒子效果的釋放速度",
```

2024-04-05 13:45 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_honey.info": "以特定速率釋放蜂蜜滴落粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_honey.info": "指定蜂蜜滴落粒子效果的釋放速度",
```

2024-04-05 13:46 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_nectar.info": "以特定速率釋放蜜蜂花粉滴落粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_nectar.info": "指定蜜蜂花粉滴落粒子效果的釋放速度",
```

2024-04-05 13:46 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_spore_blossom.info": "以特定速率釋放孢子花孢子掉落粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_spore_blossom.info": "指定孢子花孢子掉落粒子效果的釋放速度",
```

2024-04-05 13:46 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_ash.info": "以特定速率釋放靈魂沙峽谷微粒粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_ash.info": "指定靈魂沙峽谷微粒粒子效果的釋放速度",
```

2024-04-05 13:46 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_crimson_spore.info": "以特定速率釋放緋紅森林微粒粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_warped_spore.info": "指定扭曲森林微粒粒子效果的釋放速度",
```

2024-04-05 13:47 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_spore_blossom_air.info": "以特定速率釋放孢子花孢子粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_spore_blossom_air.info": "指定孢子花孢子粒子效果的釋放速度",
```

2024-04-05 13:47 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dripping_obsidian_tear.info": "以特定速率釋放黑曜石的眼淚滲出粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_obsidian_tear.info": "指定黑曜石的眼淚滴落粒子效果的釋放速度",
```

2024-04-05 13:48 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_obsidian_tear.info": "以特定速率釋放黑曜石的眼淚滴落粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_landing_obsidian_tear.info": "指定黑曜石的眼淚落地粒子效果的釋放速度",
```

2024-04-05 13:48 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_landing_obsidian_tear.info": "以特定速率釋放黑曜石的眼淚落地粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_landing_obsidian_tear.info": "指定黑曜石的眼淚落地粒子效果的釋放速度",
```

2024-04-05 13:49 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_reverse_portal.info": "以特定速率釋放傳送門（反轉）粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_reverse_portal.info": "指定傳送門（反轉）粒子效果的釋放速度",
```

2024-04-05 13:49 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_white_ash.info": "以特定速率釋放玄武岩三角洲微粒粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_white_ash.info": "指定玄武岩三角洲微粒粒子效果的釋放速度",
```

2024-04-05 13:49 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_small_flame.info": "以特定速率釋放火苗粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_small_flame.info": "指定火苗粒子效果的釋放速度",
```

2024-04-05 13:50 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_snowflake.info": "以特定速率釋放粉雪雪花粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_snowflake.info": "指定粉雪雪花粒子效果的釋放速度",
```

2024-04-05 13:50 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dripping_dripstone_lava.info": "以特定速率釋放鐘乳石滲出熔岩粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_dripstone_lava.info": "指定鐘乳石滴落熔岩粒子效果的釋放速度",
```

2024-04-05 13:50 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_dripstone_lava.info": "以特定速率釋放鐘乳石滴落熔岩粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_dripstone_lava.info": "指定鐘乳石滴落熔岩粒子效果的釋放速度",
```

2024-04-05 13:51 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dripping_dripstone_water.info": "以特定速率釋放鐘乳石滲出水粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_dripping_dripstone_water.info": "指定鐘乳石滲出水粒子效果的釋放速度",
```

2024-04-05 13:52 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_dripstone_water.info": "以特定速率釋放鐘乳石滴落水粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_falling_dripstone_water.info": "指定鐘乳石滴落水粒子效果的釋放速度",
```

2024-04-05 13:52 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_glow_squid_ink.info": "以特定速率釋放螢光魷魚噴墨粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_glow_squid_ink.info": "指定螢光魷魚噴墨粒子效果的釋放速度",
```

2024-04-05 13:52 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_glow.info": "以特定速率釋放螢光魷魚發光粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_glow.info": "指定螢光魷魚發光粒子效果的釋放速度",
```

2024-04-05 13:53 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_wax_on.info": "以特定速率釋放上蠟粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_wax_on.info": "指定上蠟粒子效果的釋放速度",
```

2024-04-05 13:53 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_wax_off.info": "以特定速率釋放除蠟粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_wax_off.info": "指定除蠟粒子效果的釋放速度",
```

2024-04-05 13:54 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "aspect.integrateddynamics.write.double.effect.particle.minecraft_scrape.info": "以特定速率釋放銅方塊除鏽粒子",
```suggestion
    "aspect.integrateddynamics.write.double.effect.particle.minecraft_scrape.info": "指定銅方塊除鏽粒子效果的釋放速度",
```

2024-04-05 13:59 UTC, rhuba8324 requested changes
改錯字、修正用詞

2024-04-05 15:07 UTC, rhuba8324 commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "item.integrateddynamics.wrench.mode.offset_side.info": "Shift + 右鍵一個位置，再右建設配來設定偏移量和方位。",
```suggestion
    "item.integrateddynamics.wrench.mode.offset_side.info": "Shift + 右鍵點擊一個位置，再對著設備點擊右鍵來設定偏移量和方位。",
```

2024-04-05 16:04 UTC, StarskyXIII requested changes

2024-04-05 16:04 UTC, StarskyXIII commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "item.integrateddynamics.wrench.mode.offset_side.info": "潛行 + 按下右鍵一個位置，再右鍵設備來設定偏移量和方位。",
```suggestion
    "item.integrateddynamics.wrench.mode.offset_side.info": "潛行 + 右鍵點擊一個位置，再對著設備點擊右鍵來設定偏移量和方位。",
```

2024-04-05 16:04 UTC, StarskyXIII commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "fluid_type.integrateddynamics.liquid_chorus": "歌萊果醬",
```suggestion
    "fluid_type.integrateddynamics.liquid_chorus": "歌萊果漿",
```

2024-04-05 16:04 UTC, StarskyXIII commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "advancement.integrateddynamics.drying.desc": "做出晾乾盆",
```suggestion
    "advancement.integrateddynamics.drying.desc": "做出乾燥盆",
```

2024-04-05 16:10 UTC, StarskyXIII requested changes

2024-04-05 16:10 UTC, StarskyXIII commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "gui.integrateddynamics.mechanical_squeezer.fluidautoeject": "自動輸出液體",
Liquid = 液體
Fluid = 流體
請將所有的 `液體` 一鍵替換為 `流體`
```suggestion
    "gui.integrateddynamics.mechanical_squeezer.fluidautoeject": "自動輸出流體",
```

2024-04-05 16:15 UTC, StarskyXIII requested changes

2024-04-05 16:15 UTC, StarskyXIII commented on MultiVersions/Forge/main/integrateddynamics/lang/zh_tw.json
> +    "operator.integrateddynamics.nbt.compound_with_boolean": "添加子標籤（布林）",
請一鍵將 `添加` 替換為 `加入`
```suggestion
    "operator.integrateddynamics.nbt.compound_with_boolean": "加入子標籤（布林）",
```

2024-05-12 04:18 UTC, StarskyXIII commented
我們還沒有準備好面對這個模組

2024-05-12 04:18 UTC, closed without merging