mods_update(Let's Do Candlelight): 更新翻譯至 v1.2.6
xMikux/ModsTranslationPack pull request #501
Opened 2023-11-04 14:53 UTC by Ylite-cola

2023-11-04 15:32 UTC, xMikux requested changes
未更新原始英文檔

2023-11-04 15:49 UTC, Ylite-cola commented
堆耶

> 未更新原始中文文檔

對耶

2023-11-13 02:30 UTC, StarskyXIII approved these changes

2023-11-13 09:40 UTC, xMikux approved these changes

2023-11-15 13:50 UTC, merged