mods_feat(Echo Chest): 新增回聲儲物箱 v8.0.0
xMikux/ModsTranslationPack pull request #502
Opened 2023-11-04 15:21 UTC by Ylite-cola

2023-11-13 02:32 UTC, StarskyXIII requested changes

2023-11-13 02:32 UTC, StarskyXIII commented on MultiVersions/Forge/main/echochest/lang/zh_tw.json
> +  "block.echochest.echo_chest.description": "收集半徑 8 格方塊內的生物掉落的物品和經驗。",
句子太長的話，建議適時的加逗號斷句
```suggestion
  "block.echochest.echo_chest.description": "收集半徑 8 格方塊內，生物掉落的物品和經驗。",
```

2023-11-14 07:52 UTC, StarskyXIII approved these changes

2023-11-15 02:01 UTC, xMikux approved these changes

2023-11-15 13:51 UTC, merged