mods_feat(Sleep Tight): 新增一夜好眠 v1.1.7
xMikux/ModsTranslationPack pull request #508
Opened 2023-11-12 17:47 UTC by Ylite-cola

2023-11-14 03:52 UTC, StarskyXIII requested changes

2023-11-14 03:52 UTC, StarskyXIII commented on MultiVersions/Forge/main/sleep_tight/lang/zh_tw.json
> +  "message.sleep_tight.encounter": "有人正在處於噩夢中",
```suggestion
  "message.sleep_tight.encounter": "有人正處於噩夢中",

```

2023-11-14 03:52 UTC, StarskyXIII commented on MultiVersions/Forge/main/sleep_tight/lang/zh_tw.json
> +  "message.sleep_tight.command.get_home_bed_nights": "在家床上的連續睡覺次數： %s",
```suggestion
  "message.sleep_tight.command.get_home_bed_nights": "在家床上的連續睡覺次數：%s",

```

2023-11-14 03:52 UTC, StarskyXIII commented on MultiVersions/Forge/main/sleep_tight/lang/zh_tw.json
> +  "message.sleep_tight.command.get_nights": "已連續入睡的夜晚天數： %s",
```suggestion
  "message.sleep_tight.command.get_nights": "已連續入睡的夜晚天數：%s",

```

2023-11-14 07:51 UTC, StarskyXIII approved these changes

2023-11-15 01:59 UTC, xMikux approved these changes

2023-11-15 13:53 UTC, merged