mods_feat(Dragonloot): 終界龍戰利品 v1.1.4
xMikux/ModsTranslationPack pull request #513
Opened 2023-11-23 11:31 UTC by Ylite-cola

40 行是補的

2023-11-29 21:13 UTC, StarskyXIII requested changes

2023-11-29 21:13 UTC, StarskyXIII commented on MultiVersions/Fabric/main/dragonloot/lang/zh_tw.json
> +  "text.autoconfig.dragonloot.option.dragon_armor_protection_helmet": "終界龍鱗頭盔護甲植",
Armor Point 我們習慣稱作 `盔甲值`
```suggestion
  "text.autoconfig.dragonloot.option.dragon_armor_protection_helmet": "終界龍鱗頭盔盔甲值",
```

2023-11-29 21:13 UTC, StarskyXIII commented on MultiVersions/Fabric/main/dragonloot/lang/zh_tw.json
> +  "text.autoconfig.dragonloot.option.dragon_armor_protection_chest": "終界龍鱗胸甲護甲植",
```suggestion
  "text.autoconfig.dragonloot.option.dragon_armor_protection_chest": "終界龍鱗胸甲盔甲值",
```

2023-11-29 21:13 UTC, StarskyXIII commented on MultiVersions/Fabric/main/dragonloot/lang/zh_tw.json
> +  "text.autoconfig.dragonloot.option.dragon_armor_protection_leggings": "終界龍鱗護腿護甲植",
```suggestion
  "text.autoconfig.dragonloot.option.dragon_armor_protection_leggings": "終界龍鱗護腿盔甲值",
```

2023-11-29 21:13 UTC, StarskyXIII commented on MultiVersions/Fabric/main/dragonloot/lang/zh_tw.json
> +  "text.autoconfig.dragonloot.option.dragon_armor_protection_boots": "終界龍鱗靴子護甲植",
```suggestion
  "text.autoconfig.dragonloot.option.dragon_armor_protection_boots": "終界龍鱗靴子盔甲值",
```

2023-11-29 21:13 UTC, StarskyXIII commented on MultiVersions/Fabric/main/dragonloot/lang/zh_tw.json
> +  "dragonloot.advancements.dragon_armor.description": "獲得全套終界龍鱗盔甲"
原版進度 `Get a full suit of Netherite armor`  是翻作 `取得全套獄髓盔甲`
```suggestion
  "dragonloot.advancements.dragon_armor.description": "取得全套終界龍鱗盔甲"
```

2023-12-02 02:43 UTC, StarskyXIII approved these changes

2023-12-02 12:39 UTC, xMikux approved these changes

2023-12-04 09:55 UTC, merged