mods_feat(Creatures and Beasts): 新增動物與野獸 v1.5.4
xMikux/ModsTranslationPack pull request #517
Opened 2023-11-30 19:44 UTC by alan198731520

2023-12-01 10:35 UTC, xMikux commented
此 PR 包括了其他模組的翻譯
需要進行調整

2024-02-17 13:02 UTC, StarskyXIII requested changes

2024-02-17 13:02 UTC, StarskyXIII commented on MultiVersions/Forge/main/creatures_and_beasts/lang/zh_tw.json
> +    "item.cnb.sporeling_overworld_egg": "主世界蘑菇怪生怪蛋",
```suggestion
    "item.cnb.sporeling_overworld_egg": "主世界蘑菇怪 生怪蛋",
```

2024-02-17 13:02 UTC, StarskyXIII commented on MultiVersions/Forge/main/creatures_and_beasts/lang/zh_tw.json
> +    "item.cnb.sporeling_nether_egg": "地獄異化蘑菇怪生怪蛋",
```suggestion
    "item.cnb.sporeling_nether_egg": "地獄異化蘑菇怪 生怪蛋",
```

2024-02-17 13:02 UTC, StarskyXIII commented on MultiVersions/Forge/main/creatures_and_beasts/lang/zh_tw.json
> +    "item.cnb.little_grebe_spawn_egg": "小鸊鷉生怪蛋",
```suggestion
    "item.cnb.little_grebe_spawn_egg": "小鸊鷉 生怪蛋",
```

2024-02-17 13:02 UTC, StarskyXIII commented on MultiVersions/Forge/main/creatures_and_beasts/lang/zh_tw.json
> +    "item.cnb.lizard_spawn_egg": "蜥蜴生怪蛋",
```suggestion
    "item.cnb.lizard_spawn_egg": "蜥蜴 生怪蛋",
```

2024-02-17 13:02 UTC, StarskyXIII commented on MultiVersions/Forge/main/creatures_and_beasts/lang/zh_tw.json
> +    "item.cnb.cindershell_spawn_egg": "燼殼獸生怪蛋",
```suggestion
    "item.cnb.cindershell_spawn_egg": "燼殼獸 生怪蛋",
```

2024-02-17 13:02 UTC, StarskyXIII commented on MultiVersions/Forge/main/creatures_and_beasts/lang/zh_tw.json
> +    "entity.sporeling_warped.hurt": "中立的蘑菇怪受傷",
```suggestion
    "entity.sporeling_warped.hurt": "中立蘑菇怪受傷",
```

2024-02-17 13:29 UTC, StarskyXIII requested changes

2024-02-17 13:29 UTC, StarskyXIII commented on MultiVersions/Forge/main/creatures_and_beasts/lang/zh_tw.json
> +    "cnb.item.tooltip.cinder_furnace": "\u00A77右鍵點擊燼殼獸以裝備在其身上"
```suggestion
    "cnb.item.tooltip.cinder_furnace": "\u00A77對著燼殼獸點擊右鍵，將熔爐裝備在牠身上"
```

2024-02-17 13:30 UTC, StarskyXIII requested changes

2024-02-17 13:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/creatures_and_beasts/lang/zh_tw.json
> +    "item.cnb.cindershell_shell_shard": "灰燼貝殼碎片",
```suggestion
    "item.cnb.cindershell_shell_shard": "燼殼碎片",
```

2024-02-17 13:35 UTC, StarskyXIII approved these changes

2024-02-17 13:37 UTC, xMikux approved these changes

2024-02-17 13:39 UTC, merged