mods_feat(Colossal Chest): 巨型儲物箱 v1.18.2-1.9.0
xMikux/ModsTranslationPack pull request #520
Opened 2023-12-02 02:33 UTC by obscure-man

2023-12-02 02:34 UTC, StarskyXIII commented
尬了，撞車

2023-12-20 02:39 UTC, StarskyXIII requested changes

2023-12-20 02:39 UTC, StarskyXIII commented on MultiVersions/Forge/main/colossalchests/lang/zh_tw.json
> +    "block.colossalchests.interface": "巨型儲物箱接口",
```suggestion
    "block.colossalchests.interface": "巨型儲物箱介面",
```

2023-12-20 02:39 UTC, StarskyXIII commented on MultiVersions/Forge/main/colossalchests/lang/zh_tw.json
> +    "multiblock.colossalchests.error.upgrade": "升級儲物箱的材料不足，需要 %s 個核心、%s 個接口和 %s 個外殼。並且材料等級至少要為%s.",
```suggestion
    "multiblock.colossalchests.error.upgrade": "升級儲物箱的材料不足，需要 %s 個核心、%s 個介面和 %s 個外殼。並且材料等級至少要為%s。",
```

2023-12-22 16:59 UTC, StarskyXIII approved these changes

2023-12-26 01:13 UTC, xMikux approved these changes

2023-12-26 01:14 UTC, merged