mods_feat(Origins): 新增起源 1.20.1-v1.10.0
xMikux/ModsTranslationPack pull request #585
Opened 2024-02-19 16:09 UTC by obscure-man

2024-04-19 07:48 UTC, StarskyXIII requested changes

2024-04-19 07:48 UTC, StarskyXIII commented on MultiVersions/Fabric/main/origins/lang/zh_tw.json
> +  "origins.gui.version_mismatch": "伺服器安裝的起源模組版本（v%1$s）和你的（v%2$s）不相同且不相容。",
```suggestion
  "origins.gui.version_mismatch": "伺服器的《起源》模組版本「v%1$s」，與你安裝的「v%2$s」不相同且不相容。",

```

2024-04-19 07:48 UTC, StarskyXIII commented on MultiVersions/Fabric/main/origins/lang/zh_tw.json
> +  "commands.origin.gui.all": "為 %s 位玩家打開指定介面",
```suggestion
  "commands.origin.gui.all": "為 %s 位玩家開啟指定介面",

```

2024-04-19 07:48 UTC, StarskyXIII commented on MultiVersions/Fabric/main/origins/lang/zh_tw.json
> +  "commands.origin.gui.layer": "為 %1$s 位玩家打開%2$s介面",
```suggestion
  "commands.origin.gui.layer": "為 %1$s 位玩家開啟%2$s介面",

```

2024-04-19 07:48 UTC, StarskyXIII commented on MultiVersions/Fabric/main/origins/lang/zh_tw.json
> +  "commands.origin.set.success.single": "將 %s 在%s種類的起源設為%s",
```suggestion
  "commands.origin.set.success.single": "將 %s 的%s起源設為%s",

```

2024-04-19 07:48 UTC, StarskyXIII commented on MultiVersions/Fabric/main/origins/lang/zh_tw.json
> +  "commands.origin.set.success.multiple": "將 %s 位玩家在%s種類的起源設為%s",
```suggestion
  "commands.origin.set.success.multiple": "將 %s 位玩家的%s起源設為%s",

```

2024-04-19 07:48 UTC, StarskyXIII commented on MultiVersions/Fabric/main/origins/lang/zh_tw.json
> +  "commands.origin.random.success.single": "為 %1$s 隨機在%3$s種類選擇到了%2$s",
```suggestion
  "commands.origin.random.success.single": "為 %1$s 的%3$s起源，隨機選擇到了%2$s",

```

2024-04-19 07:48 UTC, StarskyXIII commented on MultiVersions/Fabric/main/origins/lang/zh_tw.json
> +  "commands.origin.random.success.multiple": "為 %1$s 位玩家隨機在%2$s種類選擇一種起源",
```suggestion
  "commands.origin.random.success.multiple": "為 %1$s 位玩家隨機選擇一種%2$s起源",

```

2024-04-19 07:48 UTC, StarskyXIII commented on MultiVersions/Fabric/main/origins/lang/zh_tw.json
> +  "commands.origin.random.not_allowed": "%1$s種類並不能隨機選擇！",
```suggestion
  "commands.origin.random.not_allowed": "%1$s起源不能被隨機選擇！",

```

2024-04-19 07:48 UTC, StarskyXIII commented on MultiVersions/Fabric/main/origins/lang/zh_tw.json
> +  "commands.origin.random.success.multiple": "為 %1$s 位玩家隨機在%2$s種類選擇一種起源",
```suggestion
  "commands.origin.random.success.multiple": "為 %1$s 位玩家隨機選擇一種%2$s起源",

```

2024-04-19 07:48 UTC, StarskyXIII commented on MultiVersions/Fabric/main/origins/lang/zh_tw.json
> +  "commands.origin.random.all": "為 %1$s 位玩家隨機選擇 %2$s 個起源種類",
```suggestion
  "commands.origin.random.all": "為 %1$s 位玩家隨機選擇 %2$s 種起源",

```

2024-04-19 07:48 UTC, StarskyXIII commented on MultiVersions/Fabric/main/origins/lang/zh_tw.json
> +  "commands.origin.unregistered_in_layer": "起源%1$s並不在%2$s的類別之中！",
```suggestion
  "commands.origin.unregistered_in_layer": "%1$s起源並未登錄在%2$s的類別之中！",

```

2024-05-13 12:35 UTC, StarskyXIII submitted a review, later dismissed

2024-05-15 10:46 UTC, xMikux approved these changes

2024-05-15 10:52 UTC, StarskyXIII approved these changes

2024-05-15 10:55 UTC, merged