mods_feat(Origins: Classes): 新增起源：職業 v1.20-1.7.0
xMikux/ModsTranslationPack pull request #586
Opened 2024-02-20 12:48 UTC by obscure-man

2024-04-19 07:55 UTC, StarskyXIII requested changes

2024-04-19 07:55 UTC, StarskyXIII commented on MultiVersions/Fabric/main/origins-classes/lang/zh_tw.json
> +  "power.origins-classes.no_projectile_divergence.description": "你釋出所有的投射物都會變得更加精準。",
```suggestion
  "power.origins-classes.no_projectile_divergence.description": "你發射出所有的投射物都會變得更加精準。",

```

2024-05-13 12:12 UTC, StarskyXIII submitted a review, later dismissed

2024-05-15 10:51 UTC, xMikux approved these changes

2024-05-15 10:56 UTC, merged