mods_update(Let's Do: Beachparty): 更新翻譯至 v1.1.4
xMikux/ModsTranslationPack pull request #606
Opened 2024-04-12 16:36 UTC by Ylite-cola

2024-04-12 16:54 UTC, StarskyXIII requested changes

2024-04-12 16:54 UTC, StarskyXIII commented on MultiVersions/Forge/main/beachparty/lang/zh_tw.json
> +  "creativetab.beachparty.tab": "共度時光：沙灘派對",
itemGroup 我們習慣用 `｜` 分隔
```suggestion
  "creativetab.beachparty.tab": "共度時光｜沙灘派對",
```

2024-04-13 15:44 UTC, StarskyXIII approved these changes

2024-04-13 16:33 UTC, xMikux approved these changes

2024-04-13 16:33 UTC, merged