mods_feat(Drip Sounds: 新增滴落音效 v0.3.2
xMikux/ModsTranslationPack pull request #621
Opened 2024-05-04 11:31 UTC by Ylite-cola

2024-05-04 11:37 UTC, xMikux submitted a review, later dismissed

2024-05-04 22:37 UTC, StarskyXIII requested changes

2024-05-04 22:37 UTC, StarskyXIII commented on MultiVersions/Fabric/main/waterdripsound/lang/zh_tw.json
> +  "tooltip.config.waterdripsound.useDripstoneSounds": "若啟用，將使用 1.17 版本中增加的鐘乳石、水，熔岩的滴落聲音效。\n若禁用，則會使用此模組舊版本的音效。",
```suggestion
  "tooltip.config.waterdripsound.useDripstoneSounds": "若啟用，將使用 1.17 版本中增加的鐘乳石、水，熔岩的滴落聲音效。\n若停用，則會使用此模組舊版本的音效。",
```

2024-05-09 23:11 UTC, xMikux approved these changes

2024-05-12 03:51 UTC, StarskyXIII approved these changes

2024-05-12 12:53 UTC, merged