mods_feat(Draconic Additions): 新增龍族進化：追加 v2.2.7.10
xMikux/ModsTranslationPack pull request #627
Opened 2024-05-11 21:01 UTC by StarskyXIII

2024-05-12 09:23 UTC, notlin4 requested changes

2024-05-12 09:23 UTC, notlin4 commented on MultiVersions/Forge/main/draconicadditions/lang/zh_tw.json
> +  "info.da.chaos.cantdrop": "現在將%s從手中丟出去，似乎是個非常不好的主意。",
```suggestion
  "info.da.chaos.cantdrop": "現在將%s從手中丟出去，似乎是個非常糟糕的想法。",
```

2024-05-12 09:23 UTC, notlin4 commented on MultiVersions/Forge/main/draconicadditions/lang/zh_tw.json
> +  "info.da.chaos.cantmove": "現在移動這個%s，似乎是個非常不好的主意。",
```suggestion
  "info.da.chaos.cantmove": "現在移動這個%s，似乎是個非常糟糕的想法。",
```

2024-05-12 09:23 UTC, notlin4 commented on MultiVersions/Forge/main/draconicadditions/lang/zh_tw.json
> +  "info.da.hermal.eat.success": "沒有人能夠質疑 hermal 毒馬鈴薯的力量。",
```suggestion
  "info.da.hermal.eat.success": "沒有人能質疑 hermal 毒馬鈴薯的力量。",
```

2024-05-15 11:31 UTC, xMikux approved these changes

2024-05-15 12:43 UTC, merged