mods_feat(Little Logistics): 新增 可愛小火車 v1.4.0
xMikux/ModsTranslationPack pull request #647
Opened 2024-05-24 12:36 UTC by HankLai1207

2024-05-31 09:30 UTC, StarskyXIII requested changes

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "block.littlelogistics.locomotive_dock_rail": "車頭對接軌",
```suggestion
    "block.littlelogistics.locomotive_dock_rail": "車頭裝卸貨鐵軌",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "block.littlelogistics.car_dock_rail": "列車車廂對接軌",
```suggestion
    "block.littlelogistics.car_dock_rail": "車廂裝卸貨鐵軌",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    " ": "拖船線路配置器",
```suggestion
    "screen.littlelogistics.tug_route": "拖船線路控制器",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "screen.littlelogistics.tug_route.rename_button": "重命名節點",
```suggestion
    "screen.littlelogistics.tug_route.rename_button": "重新命名節點",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "screen.littlelogistics.tug_route.rename": "重命名 %s",
```suggestion
    "screen.littlelogistics.tug_route.rename": "重新命名 %s",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "screen.littlelogistics.locomotive.route": "目的地:",
```suggestion
    "screen.littlelogistics.locomotive.route": "目的地：",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "screen.littlelogistics.locomotive.on": "啟動引擎",
```suggestion
    "screen.littlelogistics.locomotive.on": "發動引擎",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "screen.littlelogistics.locomotive.register": "註冊表",
```suggestion
    "screen.littlelogistics.locomotive.register": "註冊",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "screen.littlelogistics.locomotive.register_info": "已註冊的車輛可以在不加載區塊的情況下行駛。",
```suggestion
    "screen.littlelogistics.locomotive.register_info": "已註冊的載具，可以在不載入區塊的情況下行駛。",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "screen.littlelogistics.locomotive.frozen": "根據服務器設置，由於車主離線，此車輛已被停用。",
```suggestion
    "screen.littlelogistics.locomotive.frozen": "根據伺服器設定，這個載具因擁有者離線而被停駛。",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "global.littlelogistics.locomotive.register_success": "已達到註冊車輛的最大數量: %s",
```suggestion
    "global.littlelogistics.locomotive.register_success": "已達到載具註冊數量的最大上限：%s",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "global.littlelogistics.locomotive.register_fail": "成功註冊了車輛，車輛已註冊: %s/%s",
```suggestion
    "global.littlelogistics.locomotive.register_fail": "成功註冊載具，載具已註冊數：%s/%s",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.tug_route.description": "點擊右鍵在路徑末尾添加節點，再次點擊同一位置可刪除節點。按住 Shift 並點擊右鍵可打開菜單。",
```suggestion
    "item.littlelogistics.tug_route.description": "在路徑末尾處點擊右鍵來新增節點；在同一位置，再次點擊右鍵可刪除節點。按住 Shift 並點擊右鍵，可開啟控制器選單。",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.tug_route.num_nodes": "路線節點: %s",
```suggestion
    "item.littlelogistics.tug_route.num_nodes": "路線節點：%s",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.tug_route.added": "已添加線路節點 X:%s Z:%s",
```suggestion
    "item.littlelogistics.tug_route.added": "已新增線路節點「X：%s Z：%s」",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.tug_route.removed": "已移除線路節點 X:%s Z:%s",
```suggestion
    "item.littlelogistics.tug_route.removed": "已移除線路節點「X：%s Z：%s」",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.conductors_wrench.description": "可用於旋轉原版鐵軌並設置 Little Logistics 模組的方塊。",
```suggestion
    "item.littlelogistics.conductors_wrench.description": "可用於旋轉原版的鐵軌，並設定《Little Logistics》模組的方塊。",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.locomotive_route.description": "右鍵點擊鐵軌在線路上添加或移除節點。",
```suggestion
    "item.littlelogistics.locomotive_route.description": "對著鐵軌點擊右鍵，在路線上新增或移除節點。",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.locomotive_route.num_nodes": "線路節點: %s",
```suggestion
    "item.littlelogistics.locomotive_route.num_nodes": "路線節點：%s",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.locomotive_route.added": "已添加線路節點 X:%s Y:%s Z:%s",
```suggestion
    "item.littlelogistics.locomotive_route.added": "已新增路線節點「X：%s Y：%s Z：%s」",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.locomotive_route.removed": "已移除線路節點 X:%s Y:%s Z:%s",
```suggestion
    "item.littlelogistics.locomotive_route.removed": "已移除路線節點「X：%s Y：%s Z：%s」",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.spring.description": "用於連接車輛。連接的車輛會在加載時等待，避免鏈條斷裂。",
```suggestion
    "item.littlelogistics.spring.description": "用於連接載具。當相連的載具位於未載入的區塊時，會試圖等待以避免斷開連結。",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.spring.notToSelf": "您無法將車輛連接到自身",
```suggestion
    "item.littlelogistics.spring.notToSelf": "您無法將載具連接至自身",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.spring.noTwoTugs": "您無法連接兩個拖船",
```suggestion
    "item.littlelogistics.spring.noTwoTugs": "您無法同時連接至兩個拖船",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.spring.noTwoLoco": "您無法連接兩個車頭",
```suggestion
    "item.littlelogistics.spring.noTwoLoco": "您無法同時連接兩個車頭",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.spring.tooFar": "由於車輛距離過遠，無法連接",
```suggestion
    "item.littlelogistics.spring.tooFar": "由於載具相距過遠，故無法連接",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.spring.noLoops": "車輛不能循環連接",
```suggestion
    "item.littlelogistics.spring.noLoops": "載具不能呈閉環連接",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.spring.badTypes": "這些車輛無法連接在一起!",
```suggestion
    "item.littlelogistics.spring.badTypes": "這些類型的載具無法連接在一起！",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.creative_capacitor": "創意電容器",
```suggestion
    "item.littlelogistics.creative_capacitor": "創造模式電容器",

```

2024-05-31 09:30 UTC, StarskyXIII commented on MultiVersions/Forge/main/littlelogistics/lang/zh_tw.json
> +    "item.littlelogistics.fishing_barge.description": "為了獲得最大收益，應該在開闊的深水域上使用長途路線",
```suggestion
  "item.littlelogistics.fishing_barge.description": "為了獲得最佳產量，建議在深水和開闊水域的長途路線上使用。",
```

2024-06-06 01:23 UTC, StarskyXIII submitted a review, later dismissed

2024-06-14 10:28 UTC, xMikux approved these changes

2024-06-14 10:47 UTC, StarskyXIII approved these changes

2024-06-14 11:00 UTC, merged