mods_feat(redstonepen): 紅石筆 v1.2.32
xMikux/ModsTranslationPack pull request #652
Opened 2024-06-05 03:30 UTC by BirdAsung

2024-06-23 07:55 UTC, notlin4 requested changes

2024-06-23 07:55 UTC, notlin4 commented on MultiVersions/Forge/main/redstonepen/lang/zh_tw.json
> +  "block.redstonepen.control_box.error.missing_closing_function_parenthesis": "缺少閉合函數括號「)」",
```suggestion
  "block.redstonepen.control_box.error.missing_closing_function_parenthesis": "應為函數右括弧「)」",
```

2024-06-23 07:55 UTC, notlin4 commented on MultiVersions/Forge/main/redstonepen/lang/zh_tw.json
> +  "block.redstonepen.control_box.error.missing_closing_parenthesis": "缺少閉合括號「)」",
```suggestion
  "block.redstonepen.control_box.error.missing_closing_parenthesis": "應為右括弧「)」",
```

2024-06-23 07:55 UTC, notlin4 commented on MultiVersions/Forge/main/redstonepen/lang/zh_tw.json
> +  "block.redstonepen.control_box.error.missing_function_arguments": "缺少函數參數（包含括號）",
```suggestion
  "block.redstonepen.control_box.error.missing_function_arguments": "應為函數引數（包含括弧）",
```

2024-06-23 07:55 UTC, notlin4 commented on MultiVersions/Forge/main/redstonepen/lang/zh_tw.json
> +  "block.redstonepen.control_box.help.2": "§n表達式§r§7 以「RESULT=TERM」賦值的形式宣告\n§7例如：「R = G & B」，每行程式碼都必須這樣寫。\n§7在開頭使用「#」標記，則代表整行皆為註釋。\n§7TERM 可以由括號「(...)」、埠、變量、運算符和函數組成。\n\n§7如果分配變數給埠（R、B、Y、G、U、D），則它會自動
```suggestion
  "block.redstonepen.control_box.help.2": "§n運算式§r§7 以「RESULT=TERM」賦值的形式宣告\n§7例如：「R = G & B」，每行程式碼都必須這樣寫。\n§7在開頭使用「#」標記，則代表整行皆為註釋。\n§7TERM 可以由括弧「(...)」、埠、變數、運算子和函數組成。\n\n§7如果分配變數給埠（R、B、Y、G、U、D），則它會自動設為輸出，任何輸入訊號的變動都將被忽略。\n§7如果在運算式中使用埠變數（尚未輸出），則會自動設為輸入。\n§7相鄰方塊的比較器輸出以「.CO」後綴讀取。例如「Y = MAX( B.CO, R, g.co, MyVar )」。\n§7即使你分配了變數給它們，「.CO」（比較器輸出）也永遠不會是 RLC 的輸出。",
```

2024-06-23 07:55 UTC, notlin4 commented on MultiVersions/Forge/main/redstonepen/lang/zh_tw.json
> +  "block.redstonepen.control_box.help.1": "§n基礎：§r§7 RLC 提供數位（開/關）和類比兩種模式\n§7（訊號強度，比較器輸出）紅石 I/O\n§7在所有方向上設定的埠，分別是紅、藍、黃、綠、上和下的首字母（R、B、Y、G、U、D）。\n§7你可以使用一組數學表達式來進行程式設計。\n§7所有程式碼都在同一個刻（tick）內計算（讀取輸入 ->計
```suggestion
  "block.redstonepen.control_box.help.1": "§n基礎：§r§7RLC 提供數位（開/關）和類比兩種模式\n§7（訊號強度，比較器輸出）紅石 I/O\n§7在所有方向上設定的埠，分別是紅、藍、黃、綠、上和下的首字母（R、B、Y、G、U、D）。\n§7你可以使用一組數學運算式來進行程式設計。\n§7所有程式碼都在同一個刻 (tick) 內計算（讀取輸入 -> 計算 -> 寫入輸出）。\n§7程式碼不區分大小寫（「R」和「r」是一樣的）。\n§7還可以設定自己的變數，它們的值將保留直到 RLC 停止。\n§7解析錯誤會以懸停的方式標記出來，並防止程式啟動。\n\n§7點擊「執行/停止」按鈕來啟動或停止程式。\n§7游標懸停在 RLC 符號上可以看到內部變數值（僅在運作時）。\n§7埠清單顯示目前訊號強度，以及埠的狀態是輸入、輸出還是未使用。\n§7複製/貼上就不多說了，你知道的 ;)",
```

2024-06-23 07:55 UTC, notlin4 commented on MultiVersions/Forge/main/redstonepen/lang/zh_tw.json
> +  "block.redstonepen.control_box.help.3": "§n算術運算子§r§7 RLC 使用整數進行運算，代表「A * 1.5」不被接受，且除法向下捨入。\n§7支援的運算子有：\n\n§7  「+」、「-」、「*」、「/」、「%」（後者為模除法）。\n\n§7變數賦值可儲存任何正或負的 32 位整數值（比你需要的大多了）。\n§7但是埠值會強制限制在有效的紅石值範
```suggestion
  "block.redstonepen.control_box.help.3": "§n算術運算子§r§7 RLC 使用整數進行運算，代表「A * 1.5」不被接受，且除法向下捨入。\n§7支援的運算子有：\n\n§7  「+」、「-」、「*」、「/」、「%」（後者為模除法）。\n\n§7變數賦值可儲存任何正或負的 32 位元整數值（比你需要的大多了）。\n§7但是埠值會強制限制在有效的紅石值範圍，即 0 到 15 之間。\n§7Int32 溢出適用時，除以 0 會產生 0 和通向地牢維度的奇點。",
```

2024-06-23 07:55 UTC, notlin4 commented on MultiVersions/Forge/main/redstonepen/lang/zh_tw.json
> +  "block.redstonepen.control_box.help.6": "§n邊緣檢測§r§7 即追蹤輸入訊號從關閉 [0] 到開啟 [>0] 以及反相的變化。\n§7上升邊緣觸發器用「.RE」後綴設置，當輸入訊號從關變為開時，在 1 刻內維持訊號強度為 15。\n§7下降邊緣觸發器用「.FE」後綴設置，當輸入訊號從開變為關時，在 1 刻內保持訊號強度為 15。\n§7例如：\n§7
```suggestion
  "block.redstonepen.control_box.help.6": "§n邊緣檢測§r§7 即追蹤輸入訊號從關閉 [0] 到開啟 [>0] 以及反相的變化。\n§7上升邊緣觸發器用「.RE」後綴設定，當輸入訊號從關變為開時，在 1 刻內維持訊號強度為 15。\n§7下降邊緣觸發器用「.FE」後綴設定，當輸入訊號從開變為關時，在 1 刻內保持訊號強度為 15。\n§7例如：\n§7\n§7 C = C + IF(R.RE OR G.FE OR Y.CO.RE, 1, 0) # 計數器 C 增加\n§7 C = CNT1(G.RE, B.RE, 10) # 使用上下計數器 1\n§7\n§7注意：雖然 RLC 可能不會每刻都在執行，但輸入端上的邊緣檢測仍然有效（即「中斷」）。\n§7PLC 中的等效項稱為 RTRIG 和 FTRIG。",
```

2024-06-23 07:55 UTC, notlin4 commented on MultiVersions/Forge/main/redstonepen/lang/zh_tw.json
> +  "block.redstonepen.control_box.help.8": "§n計數器§r§7 記錄事件發生次數。RLC 有五個上下計數器 CNT1..5，可選擇的輸入參數：\n§7\n§7N = CNTx(Iup)   # 如果 Iup > 0，計數增加\n§7N = CNTx(Iup, Idown)   # 如果 Idown > 0，計數減少到 0\n§7N = CNTx(Iup,
```suggestion
  "block.redstonepen.control_box.help.8": "§n計數器§r§7 記錄事件發生次數。RLC 有五個上下計數器 CNT1..5，可選的輸入參數：\n§7\n§7N = CNTx(Iup)   # 如果 Iup > 0，計數增加\n§7N = CNTx(Iup, Idown)   # 如果 Idown > 0，計數減少到 0\n§7N = CNTx(Iup, Idown, Max)   # 計數範圍 0..Max\n§7N = CNTx(Iup, Idown, Min, Max)   # 計數範圍 Min..Max\n§7N = CNTx(Iup, Idown, Min, Max, Reset)  # 重設回 Min\n§7\n§7N 保留新的計數器值。注意：此處偵測訊號邊緣（例如 G.RE）作為輸入來進行事件計數。\n計數器不保證刻時間的準確性（使用定時器來計時）。",
```

2024-06-23 07:55 UTC, notlin4 commented on MultiVersions/Forge/main/redstonepen/lang/zh_tw.json
> +  "block.redstonepen.control_box.tooltips.copyall": "複製程式碼到剪貼簿",
```suggestion
  "block.redstonepen.control_box.tooltips.copyall": "將程式碼複製到剪貼簿",
```

2024-06-23 07:55 UTC, notlin4 commented on MultiVersions/Forge/main/redstonepen/lang/zh_tw.json
> +  "block.redstonepen.pulse_relay.help": "在檢測到上升訊號邊緣（由關到開的脈衝控制）時，將在輸出端發出一個 1 刻（tick）的短脈衝。",
```suggestion
  "block.redstonepen.pulse_relay.help": "在檢測到上升訊號邊緣（由關到開的脈衝控制）時，將在輸出端發出一個 1 刻 (tick) 的短脈衝。",
```

2024-06-23 07:55 UTC, notlin4 commented on MultiVersions/Forge/main/redstonepen/lang/zh_tw.json
> +  "block.redstonepen.control_box.help.4": "§n關係運算子§r§7 提供數值比較：\n\n§7  「==」（等於）、「!=」（不等於）、\n§7  「>=」（大於等於）、「<=」（小於等於）、\n§7  「>」（大於）、「<」（小於）。\n\n§7如果比較結果是「false」，則表達式的值為 0，如果是「true」，則為 15。\n§7由於這些值是數字，
```suggestion
  "block.redstonepen.control_box.help.4": "§n關係運算子§r§7 提供數值比較：\n\n§7  「==」（等於）、「!=」（不等於）、\n§7  「>=」（大於等於）、「<=」（小於等於）、\n§7  「>」（大於）、「<」（小於）。\n\n§7如果比較結果是「false」，則運算式的值為 0，如果是「true」，則為 15。\n§7由於這些值是數字，你可以直接計算它們。例如「G=(R>11)/3」結果為 5 或 0。\n§7但是，更好的方法是使用 IF 函數：「G = IF( R>11, 5, 0 )」。",
```

2024-06-23 07:55 UTC, notlin4 commented on MultiVersions/Forge/main/redstonepen/lang/zh_tw.json
> +  "block.redstonepen.control_box.help.7": "§n定時器§r§7 在 PLC 中是基於訊號來運作的。\n§7RLC 中實現了三種主要定時器：TON、TOF 和 TP：\n§7TON 是一種開啟延遲。輸入訊號必須穩定開啟一段指定時間，定時器輸出才變為開啟。輸入任何關閉的訊號會立即重設定時器。\n§7TOF 則相反（關閉延遲）。\n§7TP 在檢測到輸入訊號的
```suggestion
  "block.redstonepen.control_box.help.7": "§n定時器§r§7 在 PLC 中是基於訊號來運作的。\n§7RLC 中實現了三種主要定時器：TON、TOF 和 TP：\n§7TON 是一種開啟延遲。輸入訊號必須穩定開啟一段指定時間，定時器輸出才變為開啟。輸入任何關閉的訊號會立即重設定時器。\n§7TOF 則相反（關閉延遲）。\n§7TP 在檢測到輸入訊號的上升邊緣時生成一個指定時間的脈衝。脈衝期間的任何訊號變化都會被忽略。\n§7RLC 有五個簡化的實例：\n§7\n§7 A = TON3（輸入運算式，通電延遲時長）\n§7 A = TOF2（輸入運算式，中斷供能延遲時長）\n§7 A = TP4（輸入運算式，脈衝時長）\n§7 R = TON1(Y.CO < 3, 30 * 20) # 漏斗低位警報 30 秒後觸發\n§7 R = TP1(Y.RE, 20) # 偵測器脈衝延長 1 秒",
```

2024-06-26 04:55 UTC, StarskyXIII approved these changes

2024-06-27 12:04 UTC, notlin4 approved these changes

2024-06-27 12:41 UTC, xMikux approved these changes

2024-06-27 12:42 UTC, merged