mods_feat(Iron Jetpacks): 鐵製噴射背包
xMikux/ModsTranslationPack pull request #68
Opened 2022-12-19 10:13 UTC by xMikux

備註: 由於金屬名是變數，所以將顯示類似 ``Iron 噴射背包``

2022-12-19 10:41 UTC, StarskyXIII requested changes

2022-12-19 10:41 UTC, StarskyXIII commented on assets/ironjetpacks/lang/zh_tw.json
> +  "keybind.ironjetpacks.engine": "切換引擎",
`開關` 會比較好嗎

2022-12-19 10:41 UTC, StarskyXIII commented on assets/ironjetpacks/lang/zh_tw.json
> +  "keybind.ironjetpacks.hover": "切換滯空模式",
同上

2022-12-19 10:41 UTC, StarskyXIII commented on assets/ironjetpacks/lang/zh_tw.json
> +  "tooltip.ironjetpacks.state_tooltip_layout": "%s | %s | %s",
可以換成全型的 `｜`

2022-12-19 18:31 UTC, StarskyXIII requested changes

2022-12-19 18:31 UTC, StarskyXIII commented on assets/ironjetpacks/lang/zh_tw.json
> +  "item.ironjetpacks.jetpack": "%s 製電容器",
複製貼上 bad

2022-12-19 18:31 UTC, StarskyXIII commented on assets/ironjetpacks/lang/zh_tw.json
> +  "tooltip.ironjetpacks.toggle_engine": "已切換引擎為 %s",
既然你的變數為中文字，那麼就沒必要去空格，或是用 `：`

2022-12-19 18:31 UTC, StarskyXIII commented on assets/ironjetpacks/lang/zh_tw.json
> +  "tooltip.ironjetpacks.toggle_hover": "已切換滯空模式為 %s",
同上

2022-12-19 18:31 UTC, StarskyXIII commented on assets/ironjetpacks/lang/zh_tw.json
> +  "tooltip.ironjetpacks.change_throttle": "氣閥設置為 %s",
同上上

2022-12-19 19:07 UTC, xMikux commented on assets/ironjetpacks/lang/zh_tw.json
> +  "item.ironjetpacks.jetpack": "%s 製電容器",
我還真的沒注意到 😢

2022-12-19 19:43 UTC, xMikux commented on assets/ironjetpacks/lang/zh_tw.json
> +  "tooltip.ironjetpacks.change_throttle": "氣閥設置為 %s",
![image](https://user-images.githubusercontent.com/26039249/208507082-236087c2-443b-43b8-98a8-5574b7ef6d53.png)

2022-12-19 19:43 UTC, xMikux commented on assets/ironjetpacks/lang/zh_tw.json
> +  "tooltip.ironjetpacks.change_throttle": "氣閥設置為 %s",
這仍然要嘛

2022-12-20 10:26 UTC, StarskyXIII approved these changes

2022-12-20 14:09 UTC, merged