mods_feat(Plenty Plates): 新增豐富壓力板 v8.0.0
xMikux/ModsTranslationPack pull request #680
Opened 2024-06-28 16:07 UTC by Ylite-cola

2024-06-28 21:12 UTC, StarskyXIII requested changes

2024-06-28 21:12 UTC, StarskyXIII commented on MultiVersions/Fabric/main/plentyplates/lang/zh_tw.json
> +  "block.plentyplates.pressure_plate.description": "按住 %s + 空手點擊 %s，可對壓力版進行設定",
```suggestion
  "block.plentyplates.pressure_plate.description": "按住 %s + 空手點擊 %s，可對壓力板進行設定",
```

2024-06-29 10:48 UTC, StarskyXIII approved these changes

2024-06-29 16:03 UTC, xMikux approved these changes

2024-06-30 11:00 UTC, merged