新增 Dynamic Crosshair 翻譯
xMikux/ModsTranslationPack pull request #686
Opened 2024-06-30 12:55 UTC by yichifauzi

可能需要審核 ?

2024-06-30 15:05 UTC, notlin4 commented
@yichifauzi 你先把「準星」全部替換成「準心」吧

2024-06-30 15:12 UTC, yichifauzi commented
> @yichifauzi 你先把「準星」全部替換成「準心」吧

感謝提醒 我改了

2024-07-05 11:49 UTC, StarskyXIII requested changes

2024-07-05 11:49 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.category.general": "運行方式",
```suggestion
  "dynamiccrosshair.category.general": "運作方式",
```

2024-07-05 11:49 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.hideWithScreen": "當打開界面時隱藏準心",
```suggestion
  "dynamiccrosshair.option.hideWithScreen": "當開啟介面時隱藏準心",
```

2024-07-05 11:49 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.hideWithScreen.description": "當任何界面開啟時隱藏準心。",
```suggestion
  "dynamiccrosshair.option.hideWithScreen.description": "當任何介面開啟時隱藏準心。",
```

2024-07-05 11:49 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.fixCenteredCrosshair.description": "在原版中，準心未完全居中（MC-157252）。啟用此選項可確保它始終居中。這在所有UI比例下可能無法正常運作。為了與其他模組的相容性，您可能需要停用此選項。",
```suggestion
  "dynamiccrosshair.option.fixCenteredCrosshair.description": "在原版中，準心未完全居中（MC-157252）。啟用此選項可確保它始終居中。這可能無法在所有的介面比例下正常運作。為了與其他模組的相容性，你可能需要停用此選項。",
```

2024-07-05 11:49 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.group.crosshairConfig.description": "配置準心應在何種情況下可見。在其他所有情況下，它將被隱藏。",
```suggestion
  "dynamiccrosshair.group.crosshairConfig.description": "設定準心應在何種情況下可見。在其他所有情況下，它將被隱藏。",
```

2024-07-05 11:49 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.dynamicCrosshairStyle.description": "當啟用時，使用依情況變化的樣式。\n當停用時，準心將始終保持原始款式，但仍可以根據下面的設置進行隱藏。",
```suggestion
  "dynamiccrosshair.option.dynamicCrosshairStyle.description": "當啟用時，使用依情況變化的樣式。\n當停用時，準心將始終保持原始款式，但仍可以根據下面的設定進行隱藏。",
```

2024-07-05 11:49 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairStyle.onBlock.description": "當看向方塊時的準心。根據行為設置，特定物品的準心可能會覆蓋此設置。",
```suggestion
  "dynamiccrosshair.option.crosshairStyle.onBlock.description": "當看向方塊時的準心。根據行為設置，特定物品的準心可能會覆寫此設定。",
```

2024-07-05 11:49 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairStyle.onEntity.description": "當看向實體時的準心。根據行為設置，特定物品的準心可能會覆蓋此設置。",
```suggestion
  "dynamiccrosshair.option.crosshairStyle.onEntity.description": "當看向實體時的準心。根據行為設置，特定物品的準心可能會覆寫此設定。",
```

2024-07-05 11:49 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.enableTweaks.description": "本頁的調整可以用來在無法檢測到行為變化的伺服器上配置十字準心行為。在玩單人遊戲或在其他伺服器上，你可以使用這個開關來關閉它們。",
```suggestion
  "dynamiccrosshair.option.enableTweaks.description": "本頁的調整可以用來在無法檢測到行為變化的伺服器上設定十字準心行為。在玩單人遊戲或在其他伺服器上，你可以使用這個開關來關閉它們。",
```

2024-07-05 11:49 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.requireYaclForConfigScreen": "若要通過遊戲內介面配置動態準心，請安裝 YetAnotherConfigLib！"
```suggestion
  "dynamiccrosshair.requireYaclForConfigScreen": "若要透過遊戲內的介面設定動態準心，請安裝 YetAnotherConfigLib！"
```

2024-07-05 15:15 UTC, notlin4 requested changes

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairStyle.onEntity.description": "當看向實體時的準心。根據行為設置，特定物品的準心可能會覆蓋此設置。",
```suggestion
  "dynamiccrosshair.option.crosshairStyle.onEntity.description": "當看向實體時的準心。根據行為設定，特定物品的準心可能會覆蓋此設定。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairStyle.holdingTool.description": "手持工具時的準心。根據行為設置，此準心可能會生效。",
```suggestion
  "dynamiccrosshair.option.crosshairStyle.holdingTool.description": "手持工具時的準心。根據行為設定，此準心可能會生效。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairStyle.holdingRangedWeapon.description": "手持遠程武器時的準心。根據行為設置，此準心可能會生效。",
```suggestion
  "dynamiccrosshair.option.crosshairStyle.holdingRangedWeapon.description": "手持遠程武器時的準心。根據行為設定，此準心可能會生效。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairStyle.holdingMeleeWeapon.description": "手持近戰武器時的準心。根據行為設置，此準心可能會生效。",
```suggestion
  "dynamiccrosshair.option.crosshairStyle.holdingMeleeWeapon.description": "手持近戰武器時的準心。根據行為設定，此準心可能會生效。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairStyle.holdingThrowable.description": "手持可投擲物品時的準心。根據行為設置，此準心可能會生效。",
```suggestion
  "dynamiccrosshair.option.crosshairStyle.holdingThrowable.description": "手持可投擲物品時的準心。根據行為設定，此準心可能會生效。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairStyle.holdingBlock.description": "手持可放置方塊時的準心。根據行為設置，此準心可能會生效。",
```suggestion
  "dynamiccrosshair.option.crosshairStyle.holdingBlock.description": "手持可放置方塊時的準心。根據行為設定，此準心可能會生效。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairStyle.interact.description": "看向可互動方塊時的準心修飾。根據行為設置，此準心可能會生效。",
```suggestion
  "dynamiccrosshair.option.crosshairStyle.interact.description": "看向可互動方塊時的準心修飾。根據行為設定，此準心可能會生效。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairStyle.useItem.description": "手持可使用物品時的準心修飾。根據行為設置，此準心可能會生效。",
```suggestion
  "dynamiccrosshair.option.crosshairStyle.useItem.description": "手持可使用物品時的準心修飾。根據行為設定，此準心可能會生效。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairModifiers.modIncorrectTool.description": "手持錯誤工具時的準心修飾。根據行為設置，此準心可能會生效。",
```suggestion
  "dynamiccrosshair.option.crosshairModifiers.modIncorrectTool.description": "手持錯誤工具時的準心修飾。根據行為設定，此準心可能會生效。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairStyle.shield.description": "手持盾牌時的準心修飾。根據行為設置，此準心可能會生效。",
```suggestion
  "dynamiccrosshair.option.crosshairStyle.shield.description": "手持盾牌時的準心修飾。根據行為設定，此準心可能會生效。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.additionalTools.description": "分號分隔的物品名稱列表，如：「minecraft:fire_charge」。然後這些物品將顯示其類別的十字準心。",
```suggestion
  "dynamiccrosshair.option.additionalTools.description": "分號分隔的物品名稱清單，如：「minecraft:fire_charge」。然後這些物品將顯示其類別的十字準心。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.additionalMeleeWeapons.description": "分號分隔的物品名稱列表，如：「minecraft:fire_charge」。然後這些物品將顯示其類別的十字準心。",
```suggestion
  "dynamiccrosshair.option.additionalMeleeWeapons.description": "分號分隔的物品名稱清單，如：「minecraft:fire_charge」。然後這些物品將顯示其類別的十字準心。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.additionalRangedWeapons.description": "分號分隔的物品名稱列表，如：「minecraft:fire_charge」。然後這些物品將顯示其類別的十字準心。",
```suggestion
  "dynamiccrosshair.option.additionalRangedWeapons.description": "分號分隔的物品名稱清單，如：「minecraft:fire_charge」。然後這些物品將顯示其類別的十字準心。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.additionalThrowables.description": "分號分隔的物品名稱列表，如：「minecraft:fire_charge」。然後這些物品將顯示其類別的十字準心。",
```suggestion
  "dynamiccrosshair.option.additionalThrowables.description": "分號分隔的物品名稱清單，如：「minecraft:fire_charge」。然後這些物品將顯示其類別的十字準心。",
```

2024-07-05 15:15 UTC, notlin4 commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.policy.Always": "總是",
```suggestion
  "dynamiccrosshair.policy.Always": "一律",
```

2024-07-06 01:02 UTC, StarskyXIII requested changes
統一把「設置」改為「設定」好了

2024-07-06 01:02 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairModifiers.modCorrectTool.description": "手持正確工具時的準心修飾。根據行為設置，此準心可能會生效。",
```suggestion
  "dynamiccrosshair.option.crosshairModifiers.modCorrectTool.description": "手持正確工具時的準心修飾。根據行為設定，此準心可能會生效。",
```

2024-07-06 01:02 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairConfig.holdingMeleeWeapon": "近戰武器優先覆蓋工具",
```suggestion
  "dynamiccrosshair.option.crosshairConfig.holdingMeleeWeapon": "近戰武器優先覆寫工具",
```

2024-07-06 01:02 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairConfig.meleeWeaponOnEntity": "工具/武器優先覆蓋實體",
```suggestion
  "dynamiccrosshair.option.crosshairConfig.meleeWeaponOnEntity": "工具/武器優先覆寫實體",
```

2024-07-06 01:02 UTC, StarskyXIII commented on MultiVersions/Forge/main/dynamiccrosshair/lang/zh_tw.json
> +  "dynamiccrosshair.option.crosshairConfig.meleeWeaponOnBreakableBlock": "可破壞方塊優先覆蓋武器",
```suggestion
  "dynamiccrosshair.option.crosshairConfig.meleeWeaponOnBreakableBlock": "可破壞方塊優先覆寫武器",
```

2024-07-06 02:51 UTC, yichifauzi commented
> 統一把「設置」改為「設定」好了

好的

2024-07-06 02:53 UTC, StarskyXIII approved these changes

2024-07-08 10:49 UTC, xMikux approved these changes

2024-07-08 10:54 UTC, merged