mods_feat: tofucraft
xMikux/ModsTranslationPack pull request #709
Opened 2024-07-09 15:15 UTC by PhilosophicalVitamins

2024-07-09 16:06 UTC, StarskyXIII requested changes

2024-07-09 16:06 UTC, StarskyXIII commented on MultiVersions/Forge/1.20/tofucraft/zh_tw.json
> +  "subtitles.entity.tofuspider.death": "豆腐蜘蛛：死亡",
```suggestion
  "subtitles.entity.tofuspider.death": "豆腐蜘蛛死亡",

```

2024-07-09 16:06 UTC, StarskyXIII commented on MultiVersions/Forge/1.20/tofucraft/zh_tw.json
> +  "subtitles.entity.zombie_tofunian.idle" : "殭屍豆腐村民：低吼",
```suggestion
  "subtitles.entity.zombie_tofunian.idle" : "殭屍豆腐村民吼叫",

```

2024-07-09 16:06 UTC, StarskyXIII commented on MultiVersions/Forge/1.20/tofucraft/zh_tw.json
> +  "subtitles.entity.zombie_tofunian.death" : "殭屍豆腐村民：死亡",
```suggestion
  "subtitles.entity.zombie_tofunian.death" : "殭屍豆腐村民死亡",

```

2024-07-09 16:06 UTC, StarskyXIII commented on MultiVersions/Forge/1.20/tofucraft/zh_tw.json
> +  "tofucraft.bittern_bottle.jei_desc" : "透過對著液體點擊右鍵可將豆漿凝固並獲得豆腐。",
```suggestion
  "tofucraft.bittern_bottle.jei_desc" : "透過對著流體點擊右鍵，可將豆漿凝固並獲得豆腐。",

```

2024-07-09 16:06 UTC, StarskyXIII commented on MultiVersions/Forge/1.20/tofucraft/zh_tw.json
> +  "tofucraft.blocktofukinu.jei_desc" : "可以透過用鹽鹵瓶對著豆漿右鍵獲得。",
```suggestion
  "tofucraft.blocktofukinu.jei_desc" : "對著豆漿右鍵使用鹽鹵瓶獲得。",

```

2024-07-09 16:06 UTC, StarskyXIII commented on MultiVersions/Forge/1.20/tofucraft/zh_tw.json
> +  "entity.tofucraft.slabfish.type.bagu_chan" : "小BAGU",
```suggestion
  "entity.tofucraft.slabfish.type.bagu_chan" : "小 BAGU",

```

2024-07-09 16:06 UTC, StarskyXIII commented on MultiVersions/Forge/1.20/tofucraft/zh_tw.json
> +  "tofucraft.tofu_book.tooltip2" : "如果你想閱讀這本書，請安裝 Patchouli 模組！",
```suggestion
  "tofucraft.tofu_book.tooltip2" : "如果你想閱讀這本書，請安裝《Patchouli》模組！",

```

2024-07-09 16:06 UTC, StarskyXIII commented on MultiVersions/Forge/1.20/tofucraft/zh_tw.json
> +  "itemGroup.tofucraft.tofu_foods.main_tab" : "豆腐工藝:食物",
```suggestion
  "itemGroup.tofucraft.tofu_foods.main_tab" : "豆腐工藝｜食物",

```

2024-07-09 16:06 UTC, StarskyXIII commented on MultiVersions/Forge/1.20/tofucraft/zh_tw.json
> +  "itemGroup.tofucraft.tofu_misc.main_tab" : "豆腐工藝:雜項",
```suggestion
  "itemGroup.tofucraft.tofu_misc.main_tab" : "豆腐工藝｜雜項",

```

2024-07-09 16:06 UTC, StarskyXIII commented on MultiVersions/Forge/1.20/tofucraft/zh_tw.json
> +  "itemGroup.tofucraft.tofu_tools.main_tab" : "豆腐工藝:工具",
```suggestion
  "itemGroup.tofucraft.tofu_tools.main_tab" : "豆腐工藝｜工具",

```

2024-07-09 16:06 UTC, StarskyXIII commented on MultiVersions/Forge/1.20/tofucraft/zh_tw.json
> +  "itemGroup.tofucraft.tofu_building_blocks.main_tab" : "豆腐工藝:建築方塊",
```suggestion
  "itemGroup.tofucraft.tofu_building_blocks.main_tab" : "豆腐工藝｜建築方塊",

```

2024-07-09 16:06 UTC, StarskyXIII commented on MultiVersions/Forge/1.20/tofucraft/zh_tw.json
> +  "itemGroup.tofucraft.tofu_mechanical_blocks.main_tab" : "豆腐工藝:機械",
```suggestion
  "itemGroup.tofucraft.tofu_mechanical_blocks.main_tab" : "豆腐工藝｜機械",

```

2024-07-12 10:34 UTC, StarskyXIII approved these changes

2024-07-12 10:40 UTC, StarskyXIII submitted a review, later dismissed

2024-07-12 15:51 UTC, xMikux approved these changes

2024-07-13 09:59 UTC, StarskyXIII approved these changes

2024-07-13 10:21 UTC, xMikux approved these changes

2024-07-13 10:22 UTC, merged