mods_feat(Resourcify): 新增 Resourcify v1.4.0
xMikux/ModsTranslationPack pull request #720
Opened 2024-08-10 01:00 UTC by xMikux

目前缺少細緻類別翻譯

2024-08-10 01:01 UTC, StarskyXIII commented
@notlin4 Modrinth 的分類，Crowdin 上有翻譯嗎

2024-08-10 02:07 UTC, notlin4 commented
> @notlin4 Modrinth 的分類，Crowdin 上有翻譯嗎

@StarskyXIII 沒有

2024-08-10 02:16 UTC, xMikux commented
看來我要來照字面上翻了

2024-08-10 02:45 UTC, notlin4 requested changes

2024-08-10 02:45 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.browse.bisect_ad": "託管您的伺服器在 §b§lBisectHosting§r 並使用 §b§lDIAMOND§r 代碼獲得第一個月 25%% 的折扣。",
```suggestion
  "resourcify.browse.bisect_ad": "在 §b§lBisectHosting§r 託管您的伺服器並使用代碼 §b§lDIAMOND§r 即可獲得第一個月 75%% 的折扣。",
```

2024-08-10 02:45 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.version.type.release": "發佈版",
```suggestion
  "resourcify.version.type.release": "正式版",
```

2024-08-10 02:45 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.version.published_on": "發佈於 %1$tY %1$tb %1$te",
```suggestion
  "resourcify.version.published_on": "發布於 %1$tY %1$tb %1$te",
```

2024-08-10 02:45 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.updates.updates": "更新 ",
```suggestion
  "resourcify.updates.updates": "更新",
```

2024-08-10 02:45 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.updates.wait": "請稍後等待所有更新完成再關閉介面。",
```suggestion
  "resourcify.updates.wait": "請耐心等待所有更新完成後再關閉介面。",
```

2024-08-10 02:45 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.categories.font_packs": "字形包",
```suggestion
  "resourcify.categories.font_packs": "字型包",
```

2024-08-10 02:45 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.version.type.beta": "測試版",
之前在 RPMTW 做得投票，看要不要改
```suggestion
  "resourcify.version.type.beta": "Beta 版",
```

2024-08-10 02:45 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.version.type.alpha": "預覽版",
```suggestion
  "resourcify.version.type.alpha": "Alpha 版",
```

2024-08-10 02:45 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.config.ads.description": "在瀏覽頁面上顯示小小的廣告來幫助支援開發 Resourcify。",
```suggestion
  "resourcify.config.ads.description": "在瀏覽頁面上顯示小小的廣告，幫助支持 Resourcify 的開發。",
```

2024-08-10 02:45 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.type.shaders": "光影",
```suggestion
  "resourcify.type.shaders": "光影包",
```

2024-08-10 02:45 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.project.wiki": "維基",
參考：
![image](https://github.com/user-attachments/assets/982ef825-11f7-4602-8979-0d1274997642)

```suggestion
  "resourcify.project.wiki": "wiki",
```

2024-08-10 04:35 UTC, xMikux commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.project.wiki": "維基",
![image](https://github.com/user-attachments/assets/1fb256df-2fe0-4fbf-881f-342024706c2c)
這可能要用大寫 Wiki?

2024-08-10 05:46 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.project.wiki": "維基",
應該是

2024-08-11 08:56 UTC, xMikux commented
Foliage 似乎是光線可以穿透過樹葉 但尚為想到更好的翻譯 暫時叫做 `樹葉`

2024-08-11 08:56 UTC, xMikux commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.browse.bisect_ad": "託管您的伺服器在 §b§lBisectHosting§r 並使用 §b§lDIAMOND§r 代碼獲得第一個月 25%% 的折扣。",
75% 是為了與這邊的折扣相符嘛
只是說在網站上仍然會標註 25%

2024-08-11 09:03 UTC, xMikux commented
![image](https://github.com/user-attachments/assets/07711245-850b-4741-8785-2f4fbcc6b1c2)
![image](https://github.com/user-attachments/assets/0351284b-a3c7-4e36-9840-2e4c06928757)

2024-08-11 10:07 UTC, notlin4 requested changes

2024-08-11 10:07 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.categories.8x-": "8x 或更低",
```suggestion
  "resourcify.categories.128x": "128×",
  "resourcify.categories.16x": "16×",
  "resourcify.categories.256x": "256×",
  "resourcify.categories.32x": "32×",
  "resourcify.categories.48x": "48×",
  "resourcify.categories.512x+": "512× 以上",
  "resourcify.categories.64x": "64×",
  "resourcify.categories.8x-": "8× 以下",
```

2024-08-11 10:07 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.categories.512x_and_higher": "512x 和更高",
```suggestion
  "resourcify.categories.512x_and_higher": "512× 以上",
```

2024-08-11 10:39 UTC, notlin4 requested changes

2024-08-11 10:39 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.updates.updates_available": "有 %d 個可%s！",
```suggestion
  "resourcify.updates.updates_available": "有 %d 個%s可用！",
```

2024-08-11 10:39 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.version.download_count": "%,d 下載數",
```suggestion
  "resourcify.version.download_count": "%,d 次下載",
```

2024-08-11 10:40 UTC, notlin4 commented on MultiVersions/Forge/main/resourcify/lang/zh_tw.json
> +  "resourcify.categories.foliage": "樹葉",
```suggestion
  "resourcify.categories.foliage": "樹影",
```

2024-08-11 10:53 UTC, notlin4 approved these changes

2024-08-11 10:54 UTC, StarskyXIII approved these changes

2024-08-11 11:06 UTC, merged