mods_feat(Fastload): 新增快速載入
xMikux/ModsTranslationPack pull request #87
Opened 2022-12-23 18:16 UTC by xMikux

``fastload.button.chunk_try_limit.tooltip`` 窩不確定就是了

2022-12-23 19:05 UTC, StarskyXIII requested changes

2022-12-23 19:05 UTC, StarskyXIII commented on assets/fastload/lang/zh_tw.json
> +  "fastload.button.pregen_chunk_radius.tooltip": "半徑多少區塊應在伺服器上生成直到完成。應與預先繪製半徑成相反來獲得最佳效能",
直到地形建構完成前，需要生成多少半徑的區塊。

2022-12-24 14:44 UTC, SiongSng commented on assets/fastload/lang/zh_tw.json
> +  "fastload.screen.config": "快速載入設定",
而且如果用 `快速載入設定`，聽起來的感覺不是指這個模組的 config 標題

2022-12-24 14:49 UTC, SiongSng requested changes

2022-12-24 14:49 UTC, SiongSng commented on assets/fastload/lang/zh_tw.json
> +  "fastload.button.close_loading_screen_unsafely.tooltip": "快速載入模組應該提前關掉「正在載入地形」的畫面，即使它稍微有點不安全？",
```suggestion
  "fastload.button.close_loading_screen_unsafely.tooltip": "Fastload 是否應該提前關掉「正在載入地形」的畫面，即使會有點不安全？",
```
使用模組的英文名稱應該會更好一點，另外 `稍微` 跟 `有點` 有點多餘

2022-12-24 15:29 UTC, StarskyXIII approved these changes

2022-12-24 16:54 UTC, xMikux commented on assets/fastload/lang/zh_tw.json
> +  "fastload.button.close_loading_screen_unsafely.tooltip": "快速載入模組應該提前關掉「正在載入地形」的畫面，即使它稍微有點不安全？",
感謝建議！
如果這個模組有要 PR 的話，也會將你加入為協作者
（我還在思考這個可行性，包括審核者與協作者應與一起作為協作者 Co Author PR 回原始模組專案）

2022-12-25 01:03 UTC, SiongSng commented on assets/fastload/lang/zh_tw.json
> +  "fastload.button.close_loading_screen_unsafely.tooltip": "快速載入模組應該提前關掉「正在載入地形」的畫面，即使它稍微有點不安全？",
@xMikux 我記得 Github 會自動處理這部分變成協作者

2022-12-25 01:04 UTC, SiongSng approved these changes
LGTM

2022-12-26 06:06 UTC, merged